"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc as _abc_1
import sys
import typing as _typing
from collections import abc as _abc

import grpc as _grpc
from grpc import aio as _aio

from . import contextunit_pb2 as _contextunit_pb2

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...
class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class BrainServiceStub:
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> BrainServiceAsyncStub: ...
    SearchCells: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Canonical BrainCell semantic/hybrid search.
    Request payload: {tenant_id?, query_text, limit?, min_score?, source_types?, scope_path?, user_id?}
    Response payload: {id, tenant_id, cell_kind, content, score, vector_score?, text_score?, source_type, source_ref?, scope_path?, content_hash?, confidence, visibility, metadata}
    """
    GraphSearch: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Graph Traversal
    Request payload: {tenant_id, entrypoint_ids, max_hops?, allowed_relations?}
    Response payload: {nodes: [...], edges: [...]}
    """
    CreateKGRelation: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Create Knowledge Graph relation
    Request payload: {tenant_id, source_type, source_id, relation, target_type, target_id}
    Response payload: {success}
    """
    IngestDocument: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Explicit document ingestion with enrichment/chunking semantics.
    Request payload: {tenant_id?, content, source_type, metadata?, user_id?}
    Response payload: {id, success}
    """
    UpsertCell: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Phase 3: Canonical BrainCell API
    Upsert a canonical BrainCell over current knowledge storage.
    Request payload: {tenant_id?, cell_id?, cell_kind, content, metadata?, scope_path?,
      content_hash?, source_type?, source_ref?, confidence?, visibility?, user_id?}
    Response payload: {id, tenant_id, cell_kind, source_type, scope_path, content_hash, confidence, visibility, created_at, updated_at}
    """
    QueryCells: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Query canonical BrainCells by text/scope/source/metadata.
    Request payload: {tenant_id?, query_text?, cell_kind?, source_type?, scope_path?,
      metadata_filter?, limit?, user_id?}
    Response payload stream: {id, tenant_id, cell_kind, content, metadata, score?, source_type, source_ref, scope_path, content_hash, confidence, visibility}
    """
    GetCell: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get one BrainCell by id.
    Request payload: {tenant_id?, cell_id}
    Response payload: {id, tenant_id, cell_kind, content, metadata, source_type, source_ref, scope_path, content_hash, confidence, visibility, created_at, updated_at}
    """
    DeleteDocumentationCells: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Atomically delete bounded, exact documentation cells only when every
    supplied id/content_hash target still matches in the resolved tenant.
    Request payload: {tenant_id?, targets:[{cell_id, content_hash}]}
    Response payload: {status: deleted|conflict, deleted_count, expected_count}
    """
    EnqueueCellEmbedding: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Durable asynchronous embedding enrichment. Payloads contain references
    and status only; Brain keeps cell text/provider calls internal.
    """
    ClaimCellEmbeddingJobs: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    EmbedClaimedCell: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    FailCellEmbeddingJob: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    GetCellEmbeddingStatus: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    GetEmbeddingCapability: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Cheap gate/storage readiness preflight. Does not load or call the provider."""
    AppendConversationRecord: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Conversation History
    =========================================

    Append one immutable conversation record with canonical hashes and idempotency.
    """
    QueryConversationHistory: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Run one bounded recent/older/session/trace-related projection."""
    GetConversationHistoryStats: _grpc.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]
    """Return content-free tenant statistics."""
    ApplyConversationRetention: _grpc.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]
    """Apply explicit, evidence-backed Conversation History retention."""
    ApplyExecutionTraceRetention: _grpc.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]
    """Apply age-based terminal Execution Trace retention."""
    LogTrace: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Agent Traces
    =========================================

    Log an agent execution trace
    Request payload: {tenant_id, agent_id, session_id?, graph_name?,
      tool_calls?, token_usage?, timing_ms?, security_flags?, metadata?}
    Response payload: {id, success}
    """
    GetTraces: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get traces (admin/observability)
    Request payload: {tenant_id, agent_id?, session_id?, limit?, since?}
    Response payload: {id, agent_id, graph_name, tool_calls, token_usage,
      timing_ms, security_flags, metadata, created_at}
    """
    ReserveExecutionTraceArtifact: _grpc.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]
    """Protected per-provider-attempt model-I/O artifact lifecycle. Payloads are
    closed ContextUnit contracts; immutable Trace JSON stores refs only.
    """
    FinalizeExecutionTraceArtifact: _grpc.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]
    GetExecutionTraceArtifact: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    ArchiveExecutionTraceArtifact: _grpc.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]
    RestoreExecutionTraceArtifact: _grpc.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]
    PurgeExecutionTraceArtifact: _grpc.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]
    ReportFaultOccurrence: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    UniversalDebugBus
    =========================================

    Tenant-scoped negative-experience evidence only. Occurrences/cases are
    separate from Execution Trace; no generic event API is introduced.
    Request payload: {occurrence: FaultOccurrence}; response: {case: DebugCase}.
    """
    ReportMitigationAttempt: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Request payload: {attempt: MitigationAttempt}; response: {case: DebugCase}."""
    ReportRecoveryEvidence: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Request payload: {evidence: RecoveryEvidence}; response: {case: DebugCase}."""
    ResolveDebugCase: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Request payload: {case_id, expected_case_revision, resolution_id}; response: {case: DebugCase}."""
    ReopenDebugCase: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Request payload: {case_id, trigger_occurrence_id, expected_case_revision}; response: {case: DebugCase}."""
    GetDebugCase: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Request payload: {case_id, tenant_id?}; response: {case: DebugCase}.
    Any tenant request is checked against verified caller authority.
    """
    QueryDebugCases: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Request payload: {query: DebugCaseQuery}; tenant comes only from verified context.
    One {case: DebugCase} per bounded response.
    """
    QueryRecurringFaults: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Request payload: {query: DebugCaseQuery}; recurrence requires fault_count >= 2.
    Tenant comes only from verified context; one {case: DebugCase} per response.
    """
    WriteBlackboard: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Blackboard Operations (Flat Memory)
    =========================================

    Write arbitrary data to the blackboard, return UUID
    Request payload: {tenant_id, scope_path, content, metadata?, ttl_seconds?, created_by?}
    Response payload: {id, scope_path, created_at}
    """
    ReadBlackboard: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Read one or more records by UUID(s) — STRICTLY BATCHED
    Request payload: {ids: [UUID, ...]}
    Response payload: {records: [{id, content, metadata, scope_path, created_at}]}
    """
    PruneExpiredBlackboard: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Prune expired Blackboard records for one tenant.
    Request payload: {tenant_id}
    Response payload: {deleted_count, tenant_id}
    """
    RecordSynapse: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    BrainSynapse Operations (Flat Memory Phase B)
    =========================================

    Record a BrainSynapse learning trace.
    Request payload: {tenant_id?, agent_id, action_type, action_data?, action_data_ref?,
      thought_trace_ref?, content_hash?, graph_name?, graph_run_id?, node_id?, node_name?,
      node_role?, scope_path?, context_summary?, client_id?, fault_class?, status?,
      q_action?, q_hypothesis?, q_relevance?, metadata?}
    Response payload: {id, agent_id, action_type, node_role, status, q_action,
      q_hypothesis, q_relevance, q_composite, scope_path, metadata, created_at, updated_at}
    """
    QuerySynapses: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Query BrainSynapses, ranked by q_composite and bounded by limit.
    Request payload: {tenant_id?, action_type?, agent_id?, node_role?, status?,
      scope_path?, min_q?, limit?}
    Response payload stream: one ContextUnit per Synapse row, same shape as RecordSynapse's
      response plus {graph_name, graph_run_id, node_id, node_name, action_data,
      action_data_ref, context_summary, thought_trace_ref, content_hash, fault_class}
    """
    UpdateSynapseQ: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Update Q-values/fault/status on one tenant-owned Synapse after an outcome/review.
    Request payload: {synapse_id, q_action?, q_hypothesis?, q_relevance?, fault_class?,
      status?, metadata_patch?}
    Response payload: {id, q_action, q_hypothesis, q_relevance, q_composite, updated_at}
    """
    ReportOutcomeObservation: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Store one immutable delayed outcome and let Brain resolve eligible learning.
    Request: {observation: {trace_id, graph_run_id, verdict_digest,
      observation_kind, source_authority, source_ref, occurred_at, idempotency_key}}
    Response: {observation_id, trace_id, graph_run_id, policy_version,
      decision, applied_synapse_ids}
    """
    MatchDuckDB: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    DuckDB Operations
    =========================================

    Execute high-speed DuckDB string/fuzzy matching on Parquet files
    Request payload: {tenant_id, unmatched_uri, canonical_uri}
    Response payload: {duckdb_matches: [...], duckdb_leftovers_count: int}
    """
    ListTenants: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Admin RPCs (WS-8) — require admin:read
    Cross-tenant observability owned by Brain.
    Replaces View brain_db RLS bypass (S8).
    =========================================

    List all tenants the caller may administer.
    Requires admin:read.
    Token admin:all → all tenants; else intersection with allowed_tenants.
    Request payload: {}
    Response payload: {tenants: [{id, label?, trace_count?}]}
    """
    AdminSearchTraces: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Cross-tenant trace search.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, service?, agent_id?, status?, hours?, limit?, offset?}
    Response payload: {traces: [...], total: int}
    """
    AdminGetTraceDetails: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get full details for a single trace (cross-tenant, admin-only).
    Requires admin:read.
    Request payload: {trace_id}
    Response payload: same shape as GetTraces row
    """
    AdminGetSystemAnalytics: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Cross-tenant system analytics aggregates.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {hours?, tenant_id?}
    Response payload: {analytics: {...}}
    """
    AdminGetMemoryLayerStats: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Cross-tenant Conversation History, BrainCell, and embedding-job counts.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {layer?, tenant_id?}
    Response payload: {layer_stats: {...}}
    """
    AdminGetFilterOptions: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Distinct filter values from execution traces (for admin UI dropdowns).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?}
    Response payload: {filter_options: {agent_ids, tenant_ids, graph_names, user_ids}}
    """
    AdminGetSessionTraces: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Fetch all traces for a given session_id (cross-tenant, admin-only).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {session_id, tenant_id?}
    Response payload: {traces: [...]}
    """
    AdminGetCells: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """List cells with optional tenant/kind filter (cross-tenant).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, kind?, limit?}
    Response payload: {nodes: [...]}
    """
    AdminGetAnalyticsSummary: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Rich analytics summary with per-hour breakdown, token costs, tool usage.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, hours?}
    Response payload: {analytics: {...}}
    """

@_typing.type_check_only
class BrainServiceAsyncStub(BrainServiceStub):
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    SearchCells: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Canonical BrainCell semantic/hybrid search.
    Request payload: {tenant_id?, query_text, limit?, min_score?, source_types?, scope_path?, user_id?}
    Response payload: {id, tenant_id, cell_kind, content, score, vector_score?, text_score?, source_type, source_ref?, scope_path?, content_hash?, confidence, visibility, metadata}
    """
    GraphSearch: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Graph Traversal
    Request payload: {tenant_id, entrypoint_ids, max_hops?, allowed_relations?}
    Response payload: {nodes: [...], edges: [...]}
    """
    CreateKGRelation: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Create Knowledge Graph relation
    Request payload: {tenant_id, source_type, source_id, relation, target_type, target_id}
    Response payload: {success}
    """
    IngestDocument: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Explicit document ingestion with enrichment/chunking semantics.
    Request payload: {tenant_id?, content, source_type, metadata?, user_id?}
    Response payload: {id, success}
    """
    UpsertCell: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Phase 3: Canonical BrainCell API
    Upsert a canonical BrainCell over current knowledge storage.
    Request payload: {tenant_id?, cell_id?, cell_kind, content, metadata?, scope_path?,
      content_hash?, source_type?, source_ref?, confidence?, visibility?, user_id?}
    Response payload: {id, tenant_id, cell_kind, source_type, scope_path, content_hash, confidence, visibility, created_at, updated_at}
    """
    QueryCells: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Query canonical BrainCells by text/scope/source/metadata.
    Request payload: {tenant_id?, query_text?, cell_kind?, source_type?, scope_path?,
      metadata_filter?, limit?, user_id?}
    Response payload stream: {id, tenant_id, cell_kind, content, metadata, score?, source_type, source_ref, scope_path, content_hash, confidence, visibility}
    """
    GetCell: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get one BrainCell by id.
    Request payload: {tenant_id?, cell_id}
    Response payload: {id, tenant_id, cell_kind, content, metadata, source_type, source_ref, scope_path, content_hash, confidence, visibility, created_at, updated_at}
    """
    DeleteDocumentationCells: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Atomically delete bounded, exact documentation cells only when every
    supplied id/content_hash target still matches in the resolved tenant.
    Request payload: {tenant_id?, targets:[{cell_id, content_hash}]}
    Response payload: {status: deleted|conflict, deleted_count, expected_count}
    """
    EnqueueCellEmbedding: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Durable asynchronous embedding enrichment. Payloads contain references
    and status only; Brain keeps cell text/provider calls internal.
    """
    ClaimCellEmbeddingJobs: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    EmbedClaimedCell: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    FailCellEmbeddingJob: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    GetCellEmbeddingStatus: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    GetEmbeddingCapability: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Cheap gate/storage readiness preflight. Does not load or call the provider."""
    AppendConversationRecord: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Conversation History
    =========================================

    Append one immutable conversation record with canonical hashes and idempotency.
    """
    QueryConversationHistory: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Run one bounded recent/older/session/trace-related projection."""
    GetConversationHistoryStats: _aio.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]  # type: ignore[assignment]
    """Return content-free tenant statistics."""
    ApplyConversationRetention: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Apply explicit, evidence-backed Conversation History retention."""
    ApplyExecutionTraceRetention: _aio.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]  # type: ignore[assignment]
    """Apply age-based terminal Execution Trace retention."""
    LogTrace: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Agent Traces
    =========================================

    Log an agent execution trace
    Request payload: {tenant_id, agent_id, session_id?, graph_name?,
      tool_calls?, token_usage?, timing_ms?, security_flags?, metadata?}
    Response payload: {id, success}
    """
    GetTraces: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get traces (admin/observability)
    Request payload: {tenant_id, agent_id?, session_id?, limit?, since?}
    Response payload: {id, agent_id, graph_name, tool_calls, token_usage,
      timing_ms, security_flags, metadata, created_at}
    """
    ReserveExecutionTraceArtifact: _aio.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]  # type: ignore[assignment]
    """Protected per-provider-attempt model-I/O artifact lifecycle. Payloads are
    closed ContextUnit contracts; immutable Trace JSON stores refs only.
    """
    FinalizeExecutionTraceArtifact: _aio.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]  # type: ignore[assignment]
    GetExecutionTraceArtifact: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    ArchiveExecutionTraceArtifact: _aio.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]  # type: ignore[assignment]
    RestoreExecutionTraceArtifact: _aio.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]  # type: ignore[assignment]
    PurgeExecutionTraceArtifact: _aio.UnaryUnaryMultiCallable[
        _contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit
    ]  # type: ignore[assignment]
    ReportFaultOccurrence: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    UniversalDebugBus
    =========================================

    Tenant-scoped negative-experience evidence only. Occurrences/cases are
    separate from Execution Trace; no generic event API is introduced.
    Request payload: {occurrence: FaultOccurrence}; response: {case: DebugCase}.
    """
    ReportMitigationAttempt: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Request payload: {attempt: MitigationAttempt}; response: {case: DebugCase}."""
    ReportRecoveryEvidence: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Request payload: {evidence: RecoveryEvidence}; response: {case: DebugCase}."""
    ResolveDebugCase: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Request payload: {case_id, expected_case_revision, resolution_id}; response: {case: DebugCase}."""
    ReopenDebugCase: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Request payload: {case_id, trigger_occurrence_id, expected_case_revision}; response: {case: DebugCase}."""
    GetDebugCase: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Request payload: {case_id, tenant_id?}; response: {case: DebugCase}.
    Any tenant request is checked against verified caller authority.
    """
    QueryDebugCases: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Request payload: {query: DebugCaseQuery}; tenant comes only from verified context.
    One {case: DebugCase} per bounded response.
    """
    QueryRecurringFaults: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Request payload: {query: DebugCaseQuery}; recurrence requires fault_count >= 2.
    Tenant comes only from verified context; one {case: DebugCase} per response.
    """
    WriteBlackboard: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Blackboard Operations (Flat Memory)
    =========================================

    Write arbitrary data to the blackboard, return UUID
    Request payload: {tenant_id, scope_path, content, metadata?, ttl_seconds?, created_by?}
    Response payload: {id, scope_path, created_at}
    """
    ReadBlackboard: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Read one or more records by UUID(s) — STRICTLY BATCHED
    Request payload: {ids: [UUID, ...]}
    Response payload: {records: [{id, content, metadata, scope_path, created_at}]}
    """
    PruneExpiredBlackboard: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Prune expired Blackboard records for one tenant.
    Request payload: {tenant_id}
    Response payload: {deleted_count, tenant_id}
    """
    RecordSynapse: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    BrainSynapse Operations (Flat Memory Phase B)
    =========================================

    Record a BrainSynapse learning trace.
    Request payload: {tenant_id?, agent_id, action_type, action_data?, action_data_ref?,
      thought_trace_ref?, content_hash?, graph_name?, graph_run_id?, node_id?, node_name?,
      node_role?, scope_path?, context_summary?, client_id?, fault_class?, status?,
      q_action?, q_hypothesis?, q_relevance?, metadata?}
    Response payload: {id, agent_id, action_type, node_role, status, q_action,
      q_hypothesis, q_relevance, q_composite, scope_path, metadata, created_at, updated_at}
    """
    QuerySynapses: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Query BrainSynapses, ranked by q_composite and bounded by limit.
    Request payload: {tenant_id?, action_type?, agent_id?, node_role?, status?,
      scope_path?, min_q?, limit?}
    Response payload stream: one ContextUnit per Synapse row, same shape as RecordSynapse's
      response plus {graph_name, graph_run_id, node_id, node_name, action_data,
      action_data_ref, context_summary, thought_trace_ref, content_hash, fault_class}
    """
    UpdateSynapseQ: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Update Q-values/fault/status on one tenant-owned Synapse after an outcome/review.
    Request payload: {synapse_id, q_action?, q_hypothesis?, q_relevance?, fault_class?,
      status?, metadata_patch?}
    Response payload: {id, q_action, q_hypothesis, q_relevance, q_composite, updated_at}
    """
    ReportOutcomeObservation: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Store one immutable delayed outcome and let Brain resolve eligible learning.
    Request: {observation: {trace_id, graph_run_id, verdict_digest,
      observation_kind, source_authority, source_ref, occurred_at, idempotency_key}}
    Response: {observation_id, trace_id, graph_run_id, policy_version,
      decision, applied_synapse_ids}
    """
    MatchDuckDB: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    DuckDB Operations
    =========================================

    Execute high-speed DuckDB string/fuzzy matching on Parquet files
    Request payload: {tenant_id, unmatched_uri, canonical_uri}
    Response payload: {duckdb_matches: [...], duckdb_leftovers_count: int}
    """
    ListTenants: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Admin RPCs (WS-8) — require admin:read
    Cross-tenant observability owned by Brain.
    Replaces View brain_db RLS bypass (S8).
    =========================================

    List all tenants the caller may administer.
    Requires admin:read.
    Token admin:all → all tenants; else intersection with allowed_tenants.
    Request payload: {}
    Response payload: {tenants: [{id, label?, trace_count?}]}
    """
    AdminSearchTraces: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Cross-tenant trace search.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, service?, agent_id?, status?, hours?, limit?, offset?}
    Response payload: {traces: [...], total: int}
    """
    AdminGetTraceDetails: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get full details for a single trace (cross-tenant, admin-only).
    Requires admin:read.
    Request payload: {trace_id}
    Response payload: same shape as GetTraces row
    """
    AdminGetSystemAnalytics: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Cross-tenant system analytics aggregates.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {hours?, tenant_id?}
    Response payload: {analytics: {...}}
    """
    AdminGetMemoryLayerStats: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Cross-tenant Conversation History, BrainCell, and embedding-job counts.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {layer?, tenant_id?}
    Response payload: {layer_stats: {...}}
    """
    AdminGetFilterOptions: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Distinct filter values from execution traces (for admin UI dropdowns).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?}
    Response payload: {filter_options: {agent_ids, tenant_ids, graph_names, user_ids}}
    """
    AdminGetSessionTraces: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Fetch all traces for a given session_id (cross-tenant, admin-only).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {session_id, tenant_id?}
    Response payload: {traces: [...]}
    """
    AdminGetCells: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """List cells with optional tenant/kind filter (cross-tenant).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, kind?, limit?}
    Response payload: {nodes: [...]}
    """
    AdminGetAnalyticsSummary: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Rich analytics summary with per-hour breakdown, token costs, tool usage.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, hours?}
    Response payload: {analytics: {...}}
    """

class BrainServiceServicer(metaclass=_abc_1.ABCMeta):
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    @_abc_1.abstractmethod
    def SearchCells(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Canonical BrainCell semantic/hybrid search.
        Request payload: {tenant_id?, query_text, limit?, min_score?, source_types?, scope_path?, user_id?}
        Response payload: {id, tenant_id, cell_kind, content, score, vector_score?, text_score?, source_type, source_ref?, scope_path?, content_hash?, confidence, visibility, metadata}
        """

    @_abc_1.abstractmethod
    def GraphSearch(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Graph Traversal
        Request payload: {tenant_id, entrypoint_ids, max_hops?, allowed_relations?}
        Response payload: {nodes: [...], edges: [...]}
        """

    @_abc_1.abstractmethod
    def CreateKGRelation(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Create Knowledge Graph relation
        Request payload: {tenant_id, source_type, source_id, relation, target_type, target_id}
        Response payload: {success}
        """

    @_abc_1.abstractmethod
    def IngestDocument(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Explicit document ingestion with enrichment/chunking semantics.
        Request payload: {tenant_id?, content, source_type, metadata?, user_id?}
        Response payload: {id, success}
        """

    @_abc_1.abstractmethod
    def UpsertCell(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Phase 3: Canonical BrainCell API
        Upsert a canonical BrainCell over current knowledge storage.
        Request payload: {tenant_id?, cell_id?, cell_kind, content, metadata?, scope_path?,
          content_hash?, source_type?, source_ref?, confidence?, visibility?, user_id?}
        Response payload: {id, tenant_id, cell_kind, source_type, scope_path, content_hash, confidence, visibility, created_at, updated_at}
        """

    @_abc_1.abstractmethod
    def QueryCells(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Query canonical BrainCells by text/scope/source/metadata.
        Request payload: {tenant_id?, query_text?, cell_kind?, source_type?, scope_path?,
          metadata_filter?, limit?, user_id?}
        Response payload stream: {id, tenant_id, cell_kind, content, metadata, score?, source_type, source_ref, scope_path, content_hash, confidence, visibility}
        """

    @_abc_1.abstractmethod
    def GetCell(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Get one BrainCell by id.
        Request payload: {tenant_id?, cell_id}
        Response payload: {id, tenant_id, cell_kind, content, metadata, source_type, source_ref, scope_path, content_hash, confidence, visibility, created_at, updated_at}
        """

    @_abc_1.abstractmethod
    def DeleteDocumentationCells(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Atomically delete bounded, exact documentation cells only when every
        supplied id/content_hash target still matches in the resolved tenant.
        Request payload: {tenant_id?, targets:[{cell_id, content_hash}]}
        Response payload: {status: deleted|conflict, deleted_count, expected_count}
        """

    @_abc_1.abstractmethod
    def EnqueueCellEmbedding(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Durable asynchronous embedding enrichment. Payloads contain references
        and status only; Brain keeps cell text/provider calls internal.
        """

    @_abc_1.abstractmethod
    def ClaimCellEmbeddingJobs(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]: ...
    @_abc_1.abstractmethod
    def EmbedClaimedCell(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]: ...
    @_abc_1.abstractmethod
    def FailCellEmbeddingJob(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]: ...
    @_abc_1.abstractmethod
    def GetCellEmbeddingStatus(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]: ...
    @_abc_1.abstractmethod
    def GetEmbeddingCapability(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Cheap gate/storage readiness preflight. Does not load or call the provider."""

    @_abc_1.abstractmethod
    def AppendConversationRecord(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Conversation History
        =========================================

        Append one immutable conversation record with canonical hashes and idempotency.
        """

    @_abc_1.abstractmethod
    def QueryConversationHistory(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Run one bounded recent/older/session/trace-related projection."""

    @_abc_1.abstractmethod
    def GetConversationHistoryStats(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Return content-free tenant statistics."""

    @_abc_1.abstractmethod
    def ApplyConversationRetention(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Apply explicit, evidence-backed Conversation History retention."""

    @_abc_1.abstractmethod
    def ApplyExecutionTraceRetention(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Apply age-based terminal Execution Trace retention."""

    @_abc_1.abstractmethod
    def LogTrace(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Agent Traces
        =========================================

        Log an agent execution trace
        Request payload: {tenant_id, agent_id, session_id?, graph_name?,
          tool_calls?, token_usage?, timing_ms?, security_flags?, metadata?}
        Response payload: {id, success}
        """

    @_abc_1.abstractmethod
    def GetTraces(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Get traces (admin/observability)
        Request payload: {tenant_id, agent_id?, session_id?, limit?, since?}
        Response payload: {id, agent_id, graph_name, tool_calls, token_usage,
          timing_ms, security_flags, metadata, created_at}
        """

    @_abc_1.abstractmethod
    def ReserveExecutionTraceArtifact(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Protected per-provider-attempt model-I/O artifact lifecycle. Payloads are
        closed ContextUnit contracts; immutable Trace JSON stores refs only.
        """

    @_abc_1.abstractmethod
    def FinalizeExecutionTraceArtifact(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]: ...
    @_abc_1.abstractmethod
    def GetExecutionTraceArtifact(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]: ...
    @_abc_1.abstractmethod
    def ArchiveExecutionTraceArtifact(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]: ...
    @_abc_1.abstractmethod
    def RestoreExecutionTraceArtifact(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]: ...
    @_abc_1.abstractmethod
    def PurgeExecutionTraceArtifact(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]: ...
    @_abc_1.abstractmethod
    def ReportFaultOccurrence(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        UniversalDebugBus
        =========================================

        Tenant-scoped negative-experience evidence only. Occurrences/cases are
        separate from Execution Trace; no generic event API is introduced.
        Request payload: {occurrence: FaultOccurrence}; response: {case: DebugCase}.
        """

    @_abc_1.abstractmethod
    def ReportMitigationAttempt(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Request payload: {attempt: MitigationAttempt}; response: {case: DebugCase}."""

    @_abc_1.abstractmethod
    def ReportRecoveryEvidence(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Request payload: {evidence: RecoveryEvidence}; response: {case: DebugCase}."""

    @_abc_1.abstractmethod
    def ResolveDebugCase(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Request payload: {case_id, expected_case_revision, resolution_id}; response: {case: DebugCase}."""

    @_abc_1.abstractmethod
    def ReopenDebugCase(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Request payload: {case_id, trigger_occurrence_id, expected_case_revision}; response: {case: DebugCase}."""

    @_abc_1.abstractmethod
    def GetDebugCase(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Request payload: {case_id, tenant_id?}; response: {case: DebugCase}.
        Any tenant request is checked against verified caller authority.
        """

    @_abc_1.abstractmethod
    def QueryDebugCases(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Request payload: {query: DebugCaseQuery}; tenant comes only from verified context.
        One {case: DebugCase} per bounded response.
        """

    @_abc_1.abstractmethod
    def QueryRecurringFaults(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Request payload: {query: DebugCaseQuery}; recurrence requires fault_count >= 2.
        Tenant comes only from verified context; one {case: DebugCase} per response.
        """

    @_abc_1.abstractmethod
    def WriteBlackboard(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Blackboard Operations (Flat Memory)
        =========================================

        Write arbitrary data to the blackboard, return UUID
        Request payload: {tenant_id, scope_path, content, metadata?, ttl_seconds?, created_by?}
        Response payload: {id, scope_path, created_at}
        """

    @_abc_1.abstractmethod
    def ReadBlackboard(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Read one or more records by UUID(s) — STRICTLY BATCHED
        Request payload: {ids: [UUID, ...]}
        Response payload: {records: [{id, content, metadata, scope_path, created_at}]}
        """

    @_abc_1.abstractmethod
    def PruneExpiredBlackboard(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Prune expired Blackboard records for one tenant.
        Request payload: {tenant_id}
        Response payload: {deleted_count, tenant_id}
        """

    @_abc_1.abstractmethod
    def RecordSynapse(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        BrainSynapse Operations (Flat Memory Phase B)
        =========================================

        Record a BrainSynapse learning trace.
        Request payload: {tenant_id?, agent_id, action_type, action_data?, action_data_ref?,
          thought_trace_ref?, content_hash?, graph_name?, graph_run_id?, node_id?, node_name?,
          node_role?, scope_path?, context_summary?, client_id?, fault_class?, status?,
          q_action?, q_hypothesis?, q_relevance?, metadata?}
        Response payload: {id, agent_id, action_type, node_role, status, q_action,
          q_hypothesis, q_relevance, q_composite, scope_path, metadata, created_at, updated_at}
        """

    @_abc_1.abstractmethod
    def QuerySynapses(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Query BrainSynapses, ranked by q_composite and bounded by limit.
        Request payload: {tenant_id?, action_type?, agent_id?, node_role?, status?,
          scope_path?, min_q?, limit?}
        Response payload stream: one ContextUnit per Synapse row, same shape as RecordSynapse's
          response plus {graph_name, graph_run_id, node_id, node_name, action_data,
          action_data_ref, context_summary, thought_trace_ref, content_hash, fault_class}
        """

    @_abc_1.abstractmethod
    def UpdateSynapseQ(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Update Q-values/fault/status on one tenant-owned Synapse after an outcome/review.
        Request payload: {synapse_id, q_action?, q_hypothesis?, q_relevance?, fault_class?,
          status?, metadata_patch?}
        Response payload: {id, q_action, q_hypothesis, q_relevance, q_composite, updated_at}
        """

    @_abc_1.abstractmethod
    def ReportOutcomeObservation(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Store one immutable delayed outcome and let Brain resolve eligible learning.
        Request: {observation: {trace_id, graph_run_id, verdict_digest,
          observation_kind, source_authority, source_ref, occurred_at, idempotency_key}}
        Response: {observation_id, trace_id, graph_run_id, policy_version,
          decision, applied_synapse_ids}
        """

    @_abc_1.abstractmethod
    def MatchDuckDB(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        DuckDB Operations
        =========================================

        Execute high-speed DuckDB string/fuzzy matching on Parquet files
        Request payload: {tenant_id, unmatched_uri, canonical_uri}
        Response payload: {duckdb_matches: [...], duckdb_leftovers_count: int}
        """

    @_abc_1.abstractmethod
    def ListTenants(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Admin RPCs (WS-8) — require admin:read
        Cross-tenant observability owned by Brain.
        Replaces View brain_db RLS bypass (S8).
        =========================================

        List all tenants the caller may administer.
        Requires admin:read.
        Token admin:all → all tenants; else intersection with allowed_tenants.
        Request payload: {}
        Response payload: {tenants: [{id, label?, trace_count?}]}
        """

    @_abc_1.abstractmethod
    def AdminSearchTraces(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Cross-tenant trace search.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, service?, agent_id?, status?, hours?, limit?, offset?}
        Response payload: {traces: [...], total: int}
        """

    @_abc_1.abstractmethod
    def AdminGetTraceDetails(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Get full details for a single trace (cross-tenant, admin-only).
        Requires admin:read.
        Request payload: {trace_id}
        Response payload: same shape as GetTraces row
        """

    @_abc_1.abstractmethod
    def AdminGetSystemAnalytics(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Cross-tenant system analytics aggregates.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {hours?, tenant_id?}
        Response payload: {analytics: {...}}
        """

    @_abc_1.abstractmethod
    def AdminGetMemoryLayerStats(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Cross-tenant Conversation History, BrainCell, and embedding-job counts.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {layer?, tenant_id?}
        Response payload: {layer_stats: {...}}
        """

    @_abc_1.abstractmethod
    def AdminGetFilterOptions(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Distinct filter values from execution traces (for admin UI dropdowns).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?}
        Response payload: {filter_options: {agent_ids, tenant_ids, graph_names, user_ids}}
        """

    @_abc_1.abstractmethod
    def AdminGetSessionTraces(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Fetch all traces for a given session_id (cross-tenant, admin-only).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {session_id, tenant_id?}
        Response payload: {traces: [...]}
        """

    @_abc_1.abstractmethod
    def AdminGetCells(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """List cells with optional tenant/kind filter (cross-tenant).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, kind?, limit?}
        Response payload: {nodes: [...]}
        """

    @_abc_1.abstractmethod
    def AdminGetAnalyticsSummary(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Rich analytics summary with per-hour breakdown, token costs, tool usage.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, hours?}
        Response payload: {analytics: {...}}
        """

def add_BrainServiceServicer_to_server(
    servicer: BrainServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]
) -> None: ...
