# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import contextunit_pb2 as contextunit__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in brain_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BrainServiceStub(object):
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_stream(
            "/contextunity.brain.BrainService/Search",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.GraphSearch = channel.unary_unary(
            "/contextunity.brain.BrainService/GraphSearch",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.CreateKGRelation = channel.unary_unary(
            "/contextunity.brain.BrainService/CreateKGRelation",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.Upsert = channel.unary_unary(
            "/contextunity.brain.BrainService/Upsert",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.QueryMemory = channel.unary_stream(
            "/contextunity.brain.BrainService/QueryMemory",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.UpsertCell = channel.unary_unary(
            "/contextunity.brain.BrainService/UpsertCell",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.QueryCells = channel.unary_stream(
            "/contextunity.brain.BrainService/QueryCells",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.GetCell = channel.unary_unary(
            "/contextunity.brain.BrainService/GetCell",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.EnqueueCellEmbedding = channel.unary_unary(
            "/contextunity.brain.BrainService/EnqueueCellEmbedding",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.ClaimCellEmbeddingJobs = channel.unary_unary(
            "/contextunity.brain.BrainService/ClaimCellEmbeddingJobs",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.EmbedClaimedCell = channel.unary_unary(
            "/contextunity.brain.BrainService/EmbedClaimedCell",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.FailCellEmbeddingJob = channel.unary_unary(
            "/contextunity.brain.BrainService/FailCellEmbeddingJob",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.GetCellEmbeddingStatus = channel.unary_unary(
            "/contextunity.brain.BrainService/GetCellEmbeddingStatus",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.GetEmbeddingCapability = channel.unary_unary(
            "/contextunity.brain.BrainService/GetEmbeddingCapability",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AddEpisode = channel.unary_unary(
            "/contextunity.brain.BrainService/AddEpisode",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.GetRecentEpisodes = channel.unary_stream(
            "/contextunity.brain.BrainService/GetRecentEpisodes",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.GetOldEpisodes = channel.unary_stream(
            "/contextunity.brain.BrainService/GetOldEpisodes",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.GetEpisodeStats = channel.unary_unary(
            "/contextunity.brain.BrainService/GetEpisodeStats",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.RetentionCleanup = channel.unary_unary(
            "/contextunity.brain.BrainService/RetentionCleanup",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.LogTrace = channel.unary_unary(
            "/contextunity.brain.BrainService/LogTrace",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.GetTraces = channel.unary_stream(
            "/contextunity.brain.BrainService/GetTraces",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.UpsertTaxonomy = channel.unary_unary(
            "/contextunity.brain.BrainService/UpsertTaxonomy",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.GetTaxonomy = channel.unary_stream(
            "/contextunity.brain.BrainService/GetTaxonomy",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.WriteBlackboard = channel.unary_unary(
            "/contextunity.brain.BrainService/WriteBlackboard",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.ReadBlackboard = channel.unary_unary(
            "/contextunity.brain.BrainService/ReadBlackboard",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.PruneExpiredBlackboard = channel.unary_unary(
            "/contextunity.brain.BrainService/PruneExpiredBlackboard",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.RecordSynapse = channel.unary_unary(
            "/contextunity.brain.BrainService/RecordSynapse",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.QuerySynapses = channel.unary_stream(
            "/contextunity.brain.BrainService/QuerySynapses",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.UpdateSynapseQ = channel.unary_unary(
            "/contextunity.brain.BrainService/UpdateSynapseQ",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.MatchDuckDB = channel.unary_unary(
            "/contextunity.brain.BrainService/MatchDuckDB",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.ListTenants = channel.unary_unary(
            "/contextunity.brain.BrainService/ListTenants",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AdminSearchTraces = channel.unary_unary(
            "/contextunity.brain.BrainService/AdminSearchTraces",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AdminGetTraceDetails = channel.unary_unary(
            "/contextunity.brain.BrainService/AdminGetTraceDetails",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AdminGetSystemAnalytics = channel.unary_unary(
            "/contextunity.brain.BrainService/AdminGetSystemAnalytics",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AdminGetMemoryLayerStats = channel.unary_unary(
            "/contextunity.brain.BrainService/AdminGetMemoryLayerStats",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AdminGetFilterOptions = channel.unary_unary(
            "/contextunity.brain.BrainService/AdminGetFilterOptions",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AdminGetSessionTraces = channel.unary_unary(
            "/contextunity.brain.BrainService/AdminGetSessionTraces",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AdminGetRelatedEpisodes = channel.unary_unary(
            "/contextunity.brain.BrainService/AdminGetRelatedEpisodes",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AdminSearchEpisodes = channel.unary_unary(
            "/contextunity.brain.BrainService/AdminSearchEpisodes",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AdminGetCells = channel.unary_unary(
            "/contextunity.brain.BrainService/AdminGetCells",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.AdminGetAnalyticsSummary = channel.unary_unary(
            "/contextunity.brain.BrainService/AdminGetAnalyticsSummary",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )


class BrainServiceServicer(object):
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    def Search(self, request, context):
        """Semantic/Hybrid search
        Request payload: {tenant_id, query_text, limit?, source_types?}
        Response payload: {id, content, score, source_type, metadata}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GraphSearch(self, request, context):
        """Graph Traversal
        Request payload: {tenant_id, entrypoint_ids, max_hops?, allowed_relations?}
        Response payload: {nodes: [...], edges: [...]}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateKGRelation(self, request, context):
        """Create Knowledge Graph relation
        Request payload: {tenant_id, source_type, source_id, relation, target_type, target_id}
        Response payload: {success}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Upsert(self, request, context):
        """Upsert content (generic)
        Request payload: {tenant_id, content, source_type, metadata?}
        Response payload: {id, success}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QueryMemory(self, request, context):
        """Query memory (hybrid search with provenance)
        Request payload: {tenant_id, content, filters?}
        Response payload: {content, metadata, score}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpsertCell(self, request, context):
        """Phase 3: Canonical BrainCell API
        Upsert a canonical BrainCell over current knowledge storage.
        Request payload: {tenant_id?, cell_id?, cell_kind, content, metadata?, scope_path?,
        content_hash?, source_type?, source_ref?, confidence?, visibility?, user_id?}
        Response payload: {id, tenant_id, cell_kind, source_type, scope_path, content_hash, confidence, visibility, created_at, updated_at}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QueryCells(self, request, context):
        """Query canonical BrainCells by text/scope/source/metadata.
        Request payload: {tenant_id?, query_text?, cell_kind?, source_type?, scope_path?,
        metadata_filter?, limit?, user_id?}
        Response payload stream: {id, tenant_id, cell_kind, content, metadata, score?, source_type, source_ref, scope_path, content_hash, confidence, visibility}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCell(self, request, context):
        """Get one BrainCell by id.
        Request payload: {tenant_id?, cell_id}
        Response payload: {id, tenant_id, cell_kind, content, metadata, source_type, source_ref, scope_path, content_hash, confidence, visibility, created_at, updated_at}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EnqueueCellEmbedding(self, request, context):
        """Durable asynchronous embedding enrichment. Payloads contain references
        and status only; Brain keeps cell text/provider calls internal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ClaimCellEmbeddingJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EmbedClaimedCell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FailCellEmbeddingJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCellEmbeddingStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEmbeddingCapability(self, request, context):
        """Cheap gate/storage readiness preflight. Does not load or call the provider."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddEpisode(self, request, context):
        """=========================================
        NewsEngine Operations
        =========================================

        =========================================
        Episodic & Entity Memory
        =========================================

        Add conversation episode
        Request payload: {user_id, tenant_id, session_id?, content, metadata?}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRecentEpisodes(self, request, context):
        """Get recent episodes for a user
        Request payload: {tenant_id, user_id, limit?}
        Response payload: {id, content, metadata, created_at}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetOldEpisodes(self, request, context):
        """Get episodes older than N days (retention / synthesis)
        Request payload: {tenant_id, older_than_days?, limit?}
        Response payload: {id, user_id, content, metadata, created_at, source_hash?, graph_run_id?}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEpisodeStats(self, request, context):
        """Get episode count and date range for a tenant
        Request payload: {tenant_id}
        Response payload: {total, oldest, newest, tenant_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RetentionCleanup(self, request, context):
        """Delete old episodes for a tenant, optionally restricted to explicit IDs
        Request payload: {tenant_id, older_than_days, episode_ids?}
        Response payload: {deleted_count}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LogTrace(self, request, context):
        """=========================================
        Agent Traces
        =========================================

        Log an agent execution trace
        Request payload: {tenant_id, agent_id, session_id?, graph_name?,
        tool_calls?, token_usage?, timing_ms?, security_flags?, metadata?}
        Response payload: {id, success}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTraces(self, request, context):
        """Get traces (admin/observability)
        Request payload: {tenant_id, agent_id?, session_id?, limit?, since?}
        Response payload: {id, agent_id, graph_name, tool_calls, token_usage,
        timing_ms, security_flags, metadata, created_at}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpsertTaxonomy(self, request, context):
        """=========================================
        Taxonomy Operations
        =========================================

        Upsert taxonomy entry
        Request payload: {tenant_id, domain, name, path, keywords?, metadata?}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTaxonomy(self, request, context):
        """Get taxonomy entries
        Request payload: {tenant_id, domain?}
        Response payload: {domain, name, path, keywords, metadata}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WriteBlackboard(self, request, context):
        """=========================================
        Blackboard Operations (Flat Memory)
        =========================================

        Write arbitrary data to the blackboard, return UUID
        Request payload: {tenant_id, scope_path, content, metadata?, ttl_seconds?, created_by?}
        Response payload: {id, scope_path, created_at}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadBlackboard(self, request, context):
        """Read one or more records by UUID(s) — STRICTLY BATCHED
        Request payload: {ids: [UUID, ...]}
        Response payload: {records: [{id, content, metadata, scope_path, created_at}]}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PruneExpiredBlackboard(self, request, context):
        """Prune expired Blackboard records for one tenant.
        Request payload: {tenant_id}
        Response payload: {deleted_count, tenant_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RecordSynapse(self, request, context):
        """=========================================
        BrainSynapse Operations (Flat Memory Phase B)
        =========================================

        Record a BrainSynapse learning trace.
        Request payload: {tenant_id?, agent_id, action_type, action_data?, action_data_ref?,
        thought_trace_ref?, content_hash?, graph_name?, graph_run_id?, node_id?, node_name?,
        node_role?, scope_path?, context_summary?, client_id?, fault_class?, status?,
        q_action?, q_hypothesis?, q_relevance?, metadata?}
        Response payload: {id, agent_id, action_type, node_role, status, q_action,
        q_hypothesis, q_relevance, q_composite, scope_path, metadata, created_at, updated_at}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QuerySynapses(self, request, context):
        """Query BrainSynapses, ranked by q_composite and bounded by limit.
        Request payload: {tenant_id?, action_type?, agent_id?, node_role?, status?,
        scope_path?, min_q?, limit?}
        Response payload stream: one ContextUnit per Synapse row, same shape as RecordSynapse's
        response plus {graph_name, graph_run_id, node_id, node_name, action_data,
        action_data_ref, context_summary, thought_trace_ref, content_hash, fault_class}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateSynapseQ(self, request, context):
        """Update Q-values/fault/status on one tenant-owned Synapse after an outcome/review.
        Request payload: {synapse_id, q_action?, q_hypothesis?, q_relevance?, fault_class?,
        status?, metadata_patch?}
        Response payload: {id, q_action, q_hypothesis, q_relevance, q_composite, updated_at}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MatchDuckDB(self, request, context):
        """=========================================
        DuckDB Operations
        =========================================

        Execute high-speed DuckDB string/fuzzy matching on Parquet files
        Request payload: {tenant_id, unmatched_uri, canonical_uri}
        Response payload: {duckdb_matches: [...], duckdb_leftovers_count: int}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTenants(self, request, context):
        """=========================================
        Admin RPCs (WS-8) — require admin:read
        Cross-tenant observability owned by Brain.
        Replaces View brain_db RLS bypass (S8).
        =========================================

        List all tenants the caller may administer.
        Requires admin:read.
        Token admin:all → all tenants; else intersection with allowed_tenants.
        Request payload: {}
        Response payload: {tenants: [{id, label?, trace_count?}]}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdminSearchTraces(self, request, context):
        """Cross-tenant trace search.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, service?, agent_id?, status?, hours?, limit?, offset?}
        Response payload: {traces: [...], total: int}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdminGetTraceDetails(self, request, context):
        """Get full details for a single trace (cross-tenant, admin-only).
        Requires admin:read.
        Request payload: {trace_id}
        Response payload: same shape as GetTraces row
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdminGetSystemAnalytics(self, request, context):
        """Cross-tenant system analytics aggregates.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {hours?, tenant_id?}
        Response payload: {analytics: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdminGetMemoryLayerStats(self, request, context):
        """Cross-tenant memory layer stats (episodes, knowledge node counts).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {layer?, tenant_id?}
        Response payload: {layer_stats: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdminGetFilterOptions(self, request, context):
        """Distinct filter values from agent_traces (for admin UI dropdowns).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?}
        Response payload: {filter_options: {agent_ids, tenant_ids, graph_names, user_ids}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdminGetSessionTraces(self, request, context):
        """Fetch all traces for a given session_id (cross-tenant, admin-only).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {session_id, tenant_id?}
        Response payload: {traces: [...]}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdminGetRelatedEpisodes(self, request, context):
        """Fetch episodic_events related to a trace by trace_id (cross-tenant).
        Requires admin:read.
        Tenant scope is resolved from the trace's own tenant_id (by-id lookup).
        Request payload: {trace_id}
        Response payload: {episodes: [...]}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdminSearchEpisodes(self, request, context):
        """Cross-tenant episodic event search with pagination.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, user_id?, session_id?, hours?, limit?, offset?}
        Response payload: {events: [...], total: int}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdminGetCells(self, request, context):
        """List cells with optional tenant/kind filter (cross-tenant).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, kind?, limit?}
        Response payload: {nodes: [...]}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdminGetAnalyticsSummary(self, request, context):
        """Rich analytics summary with per-hour breakdown, token costs, tool usage.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, hours?}
        Response payload: {analytics: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Search": grpc.unary_stream_rpc_method_handler(
            servicer.Search,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "GraphSearch": grpc.unary_unary_rpc_method_handler(
            servicer.GraphSearch,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "CreateKGRelation": grpc.unary_unary_rpc_method_handler(
            servicer.CreateKGRelation,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "Upsert": grpc.unary_unary_rpc_method_handler(
            servicer.Upsert,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "QueryMemory": grpc.unary_stream_rpc_method_handler(
            servicer.QueryMemory,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "UpsertCell": grpc.unary_unary_rpc_method_handler(
            servicer.UpsertCell,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "QueryCells": grpc.unary_stream_rpc_method_handler(
            servicer.QueryCells,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "GetCell": grpc.unary_unary_rpc_method_handler(
            servicer.GetCell,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "EnqueueCellEmbedding": grpc.unary_unary_rpc_method_handler(
            servicer.EnqueueCellEmbedding,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "ClaimCellEmbeddingJobs": grpc.unary_unary_rpc_method_handler(
            servicer.ClaimCellEmbeddingJobs,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "EmbedClaimedCell": grpc.unary_unary_rpc_method_handler(
            servicer.EmbedClaimedCell,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "FailCellEmbeddingJob": grpc.unary_unary_rpc_method_handler(
            servicer.FailCellEmbeddingJob,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "GetCellEmbeddingStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetCellEmbeddingStatus,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "GetEmbeddingCapability": grpc.unary_unary_rpc_method_handler(
            servicer.GetEmbeddingCapability,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AddEpisode": grpc.unary_unary_rpc_method_handler(
            servicer.AddEpisode,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "GetRecentEpisodes": grpc.unary_stream_rpc_method_handler(
            servicer.GetRecentEpisodes,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "GetOldEpisodes": grpc.unary_stream_rpc_method_handler(
            servicer.GetOldEpisodes,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "GetEpisodeStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetEpisodeStats,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "RetentionCleanup": grpc.unary_unary_rpc_method_handler(
            servicer.RetentionCleanup,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "LogTrace": grpc.unary_unary_rpc_method_handler(
            servicer.LogTrace,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "GetTraces": grpc.unary_stream_rpc_method_handler(
            servicer.GetTraces,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "UpsertTaxonomy": grpc.unary_unary_rpc_method_handler(
            servicer.UpsertTaxonomy,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "GetTaxonomy": grpc.unary_stream_rpc_method_handler(
            servicer.GetTaxonomy,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "WriteBlackboard": grpc.unary_unary_rpc_method_handler(
            servicer.WriteBlackboard,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "ReadBlackboard": grpc.unary_unary_rpc_method_handler(
            servicer.ReadBlackboard,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "PruneExpiredBlackboard": grpc.unary_unary_rpc_method_handler(
            servicer.PruneExpiredBlackboard,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "RecordSynapse": grpc.unary_unary_rpc_method_handler(
            servicer.RecordSynapse,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "QuerySynapses": grpc.unary_stream_rpc_method_handler(
            servicer.QuerySynapses,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "UpdateSynapseQ": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateSynapseQ,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "MatchDuckDB": grpc.unary_unary_rpc_method_handler(
            servicer.MatchDuckDB,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "ListTenants": grpc.unary_unary_rpc_method_handler(
            servicer.ListTenants,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AdminSearchTraces": grpc.unary_unary_rpc_method_handler(
            servicer.AdminSearchTraces,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AdminGetTraceDetails": grpc.unary_unary_rpc_method_handler(
            servicer.AdminGetTraceDetails,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AdminGetSystemAnalytics": grpc.unary_unary_rpc_method_handler(
            servicer.AdminGetSystemAnalytics,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AdminGetMemoryLayerStats": grpc.unary_unary_rpc_method_handler(
            servicer.AdminGetMemoryLayerStats,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AdminGetFilterOptions": grpc.unary_unary_rpc_method_handler(
            servicer.AdminGetFilterOptions,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AdminGetSessionTraces": grpc.unary_unary_rpc_method_handler(
            servicer.AdminGetSessionTraces,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AdminGetRelatedEpisodes": grpc.unary_unary_rpc_method_handler(
            servicer.AdminGetRelatedEpisodes,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AdminSearchEpisodes": grpc.unary_unary_rpc_method_handler(
            servicer.AdminSearchEpisodes,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AdminGetCells": grpc.unary_unary_rpc_method_handler(
            servicer.AdminGetCells,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "AdminGetAnalyticsSummary": grpc.unary_unary_rpc_method_handler(
            servicer.AdminGetAnalyticsSummary,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("contextunity.brain.BrainService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("contextunity.brain.BrainService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class BrainService(object):
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextunity.brain.BrainService/Search",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GraphSearch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/GraphSearch",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateKGRelation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/CreateKGRelation",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Upsert(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/Upsert",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def QueryMemory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextunity.brain.BrainService/QueryMemory",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpsertCell(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/UpsertCell",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def QueryCells(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextunity.brain.BrainService/QueryCells",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCell(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/GetCell",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EnqueueCellEmbedding(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/EnqueueCellEmbedding",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ClaimCellEmbeddingJobs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/ClaimCellEmbeddingJobs",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EmbedClaimedCell(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/EmbedClaimedCell",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FailCellEmbeddingJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/FailCellEmbeddingJob",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCellEmbeddingStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/GetCellEmbeddingStatus",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetEmbeddingCapability(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/GetEmbeddingCapability",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddEpisode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AddEpisode",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetRecentEpisodes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextunity.brain.BrainService/GetRecentEpisodes",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetOldEpisodes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextunity.brain.BrainService/GetOldEpisodes",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetEpisodeStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/GetEpisodeStats",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RetentionCleanup(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/RetentionCleanup",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LogTrace(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/LogTrace",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTraces(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextunity.brain.BrainService/GetTraces",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpsertTaxonomy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/UpsertTaxonomy",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTaxonomy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextunity.brain.BrainService/GetTaxonomy",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def WriteBlackboard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/WriteBlackboard",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadBlackboard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/ReadBlackboard",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PruneExpiredBlackboard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/PruneExpiredBlackboard",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RecordSynapse(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/RecordSynapse",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def QuerySynapses(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextunity.brain.BrainService/QuerySynapses",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateSynapseQ(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/UpdateSynapseQ",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MatchDuckDB(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/MatchDuckDB",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTenants(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/ListTenants",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdminSearchTraces(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AdminSearchTraces",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdminGetTraceDetails(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AdminGetTraceDetails",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdminGetSystemAnalytics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AdminGetSystemAnalytics",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdminGetMemoryLayerStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AdminGetMemoryLayerStats",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdminGetFilterOptions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AdminGetFilterOptions",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdminGetSessionTraces(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AdminGetSessionTraces",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdminGetRelatedEpisodes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AdminGetRelatedEpisodes",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdminSearchEpisodes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AdminSearchEpisodes",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdminGetCells(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AdminGetCells",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdminGetAnalyticsSummary(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.brain.BrainService/AdminGetAnalyticsSummary",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
