"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc as _abc_1
import sys
import typing as _typing
from collections import abc as _abc

import grpc as _grpc
from grpc import aio as _aio

from . import contextunit_pb2 as _contextunit_pb2

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...
class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class BrainServiceStub:
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> BrainServiceAsyncStub: ...
    Search: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Semantic/Hybrid search
    Request payload: {tenant_id, query_text, limit?, source_types?}
    Response payload: {id, content, score, source_type, metadata}
    """
    GraphSearch: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Graph Traversal
    Request payload: {tenant_id, entrypoint_ids, max_hops?, allowed_relations?}
    Response payload: {nodes: [...], edges: [...]}
    """
    CreateKGRelation: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Create Knowledge Graph relation
    Request payload: {tenant_id, source_type, source_id, relation, target_type, target_id}
    Response payload: {success}
    """
    Upsert: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Upsert content (generic)
    Request payload: {tenant_id, content, source_type, metadata?}
    Response payload: {id, success}
    """
    QueryMemory: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Query memory (hybrid search with provenance)
    Request payload: {tenant_id, content, filters?}
    Response payload: {content, metadata, score}
    """
    AddEpisode: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Episodic & Entity Memory
    =========================================

    Add conversation episode
    Request payload: {user_id, tenant_id, session_id?, content, metadata?}
    """
    GetRecentEpisodes: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get recent episodes for a user
    Request payload: {tenant_id, user_id, limit?}
    Response payload: {id, content, metadata, created_at}
    """
    UpsertFact: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Upsert user fact
    Request payload: {user_id, tenant_id, key, value, confidence?, source_id?}
    """
    GetUserFacts: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get all facts for a user
    Request payload: {tenant_id, user_id}
    Response payload: {fact_key, fact_value, confidence, updated_at}
    """
    GetEpisodeStats: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get episode count and date range for a tenant
    Request payload: {tenant_id}
    Response payload: {total, oldest, newest, tenant_id}
    """
    RetentionCleanup: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Delete old episodes for a tenant, optionally restricted to explicit IDs
    Request payload: {tenant_id, older_than_days, episode_ids?}
    Response payload: {deleted_count}
    """
    LogTrace: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Agent Traces
    =========================================

    Log an agent execution trace
    Request payload: {tenant_id, agent_id, session_id?, graph_name?,
      tool_calls?, token_usage?, timing_ms?, security_flags?, metadata?}
    Response payload: {id, success}
    """
    GetTraces: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get traces (admin/observability)
    Request payload: {tenant_id, agent_id?, session_id?, limit?, since?}
    Response payload: {id, agent_id, graph_name, tool_calls, token_usage,
      timing_ms, security_flags, metadata, created_at}
    """
    UpsertTaxonomy: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Taxonomy Operations
    =========================================

    Upsert taxonomy entry
    Request payload: {tenant_id, domain, name, path, keywords?, metadata?}
    """
    GetTaxonomy: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get taxonomy entries
    Request payload: {tenant_id, domain?}
    Response payload: {domain, name, path, keywords, metadata}
    """
    WriteBlackboard: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Blackboard Operations (Flat Memory)
    =========================================

    Write arbitrary data to the blackboard, return UUID
    Request payload: {tenant_id, scope_path, content, metadata?, ttl_seconds?, created_by?}
    Response payload: {id, scope_path, created_at}
    """
    ReadBlackboard: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Read one or more records by UUID(s) — STRICTLY BATCHED
    Request payload: {ids: [UUID, ...]}
    Response payload: {records: [{id, content, metadata, scope_path, created_at}]}
    """
    RecordSynapse: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    BrainSynapse Operations (Flat Memory Phase B)
    =========================================

    Record a BrainSynapse learning trace.
    Request payload: {tenant_id?, agent_id, action_type, action_data?, action_data_ref?,
      thought_trace_ref?, content_hash?, graph_name?, graph_run_id?, node_id?, node_name?,
      node_role?, scope_path?, context_summary?, client_id?, fault_class?, status?,
      q_action?, q_hypothesis?, q_relevance?, metadata?}
    Response payload: {id, agent_id, action_type, node_role, status, q_action,
      q_hypothesis, q_relevance, q_composite, scope_path, metadata, created_at, updated_at}
    """
    QuerySynapses: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Query BrainSynapses, ranked by q_composite and bounded by limit.
    Request payload: {tenant_id?, action_type?, agent_id?, node_role?, status?,
      scope_path?, min_q?, limit?}
    Response payload stream: one ContextUnit per Synapse row, same shape as RecordSynapse's
      response plus {graph_name, graph_run_id, node_id, node_name, action_data,
      action_data_ref, context_summary, thought_trace_ref, content_hash, fault_class}
    """
    UpdateSynapseQ: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Update Q-values/fault/status on one tenant-owned Synapse after an outcome/review.
    Request payload: {synapse_id, q_action?, q_hypothesis?, q_relevance?, fault_class?,
      status?, metadata_patch?}
    Response payload: {id, q_action, q_hypothesis, q_relevance, q_composite, updated_at}
    """
    MatchDuckDB: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    DuckDB Operations
    =========================================

    Execute high-speed DuckDB string/fuzzy matching on Parquet files
    Request payload: {tenant_id, unmatched_uri, canonical_uri}
    Response payload: {duckdb_matches: [...], duckdb_leftovers_count: int}
    """
    ListTenants: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Admin RPCs (WS-8) — require admin:read
    Cross-tenant observability owned by Brain.
    Replaces View brain_db RLS bypass (S8).
    =========================================

    List all tenants the caller may administer.
    Requires admin:read.
    Token admin:all → all tenants; else intersection with allowed_tenants.
    Request payload: {}
    Response payload: {tenants: [{id, label?, trace_count?}]}
    """
    AdminSearchTraces: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Cross-tenant trace search.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, service?, agent_id?, status?, hours?, limit?, offset?}
    Response payload: {traces: [...], total: int}
    """
    AdminGetTraceDetails: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get full details for a single trace (cross-tenant, admin-only).
    Requires admin:read.
    Request payload: {trace_id}
    Response payload: same shape as GetTraces row
    """
    AdminGetSystemAnalytics: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Cross-tenant system analytics aggregates.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {hours?, tenant_id?}
    Response payload: {analytics: {...}}
    """
    AdminGetMemoryLayerStats: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Cross-tenant memory layer stats (episodes, knowledge node counts).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {layer?, tenant_id?}
    Response payload: {layer_stats: {...}}
    """
    AdminGetFilterOptions: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Distinct filter values from agent_traces (for admin UI dropdowns).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?}
    Response payload: {filter_options: {agent_ids, tenant_ids, graph_names, user_ids}}
    """
    AdminGetSessionTraces: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Fetch all traces for a given session_id (cross-tenant, admin-only).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {session_id, tenant_id?}
    Response payload: {traces: [...]}
    """
    AdminGetRelatedEpisodes: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Fetch episodic_events related to a trace by trace_id (cross-tenant).
    Requires admin:read.
    Tenant scope is resolved from the trace's own tenant_id (by-id lookup).
    Request payload: {trace_id}
    Response payload: {episodes: [...]}
    """
    AdminSearchEpisodes: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Cross-tenant episodic event search with pagination.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, user_id?, session_id?, hours?, limit?, offset?}
    Response payload: {events: [...], total: int}
    """
    AdminGetCells: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """List cells with optional tenant/kind filter (cross-tenant).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, kind?, limit?}
    Response payload: {nodes: [...]}
    """
    AdminGetAnalyticsSummary: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Rich analytics summary with per-hour breakdown, token costs, tool usage.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, hours?}
    Response payload: {analytics: {...}}
    """

@_typing.type_check_only
class BrainServiceAsyncStub(BrainServiceStub):
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Search: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Semantic/Hybrid search
    Request payload: {tenant_id, query_text, limit?, source_types?}
    Response payload: {id, content, score, source_type, metadata}
    """
    GraphSearch: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Graph Traversal
    Request payload: {tenant_id, entrypoint_ids, max_hops?, allowed_relations?}
    Response payload: {nodes: [...], edges: [...]}
    """
    CreateKGRelation: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Create Knowledge Graph relation
    Request payload: {tenant_id, source_type, source_id, relation, target_type, target_id}
    Response payload: {success}
    """
    Upsert: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Upsert content (generic)
    Request payload: {tenant_id, content, source_type, metadata?}
    Response payload: {id, success}
    """
    QueryMemory: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Query memory (hybrid search with provenance)
    Request payload: {tenant_id, content, filters?}
    Response payload: {content, metadata, score}
    """
    AddEpisode: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Episodic & Entity Memory
    =========================================

    Add conversation episode
    Request payload: {user_id, tenant_id, session_id?, content, metadata?}
    """
    GetRecentEpisodes: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get recent episodes for a user
    Request payload: {tenant_id, user_id, limit?}
    Response payload: {id, content, metadata, created_at}
    """
    UpsertFact: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Upsert user fact
    Request payload: {user_id, tenant_id, key, value, confidence?, source_id?}
    """
    GetUserFacts: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get all facts for a user
    Request payload: {tenant_id, user_id}
    Response payload: {fact_key, fact_value, confidence, updated_at}
    """
    GetEpisodeStats: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get episode count and date range for a tenant
    Request payload: {tenant_id}
    Response payload: {total, oldest, newest, tenant_id}
    """
    RetentionCleanup: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Delete old episodes for a tenant, optionally restricted to explicit IDs
    Request payload: {tenant_id, older_than_days, episode_ids?}
    Response payload: {deleted_count}
    """
    LogTrace: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Agent Traces
    =========================================

    Log an agent execution trace
    Request payload: {tenant_id, agent_id, session_id?, graph_name?,
      tool_calls?, token_usage?, timing_ms?, security_flags?, metadata?}
    Response payload: {id, success}
    """
    GetTraces: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get traces (admin/observability)
    Request payload: {tenant_id, agent_id?, session_id?, limit?, since?}
    Response payload: {id, agent_id, graph_name, tool_calls, token_usage,
      timing_ms, security_flags, metadata, created_at}
    """
    UpsertTaxonomy: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Taxonomy Operations
    =========================================

    Upsert taxonomy entry
    Request payload: {tenant_id, domain, name, path, keywords?, metadata?}
    """
    GetTaxonomy: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get taxonomy entries
    Request payload: {tenant_id, domain?}
    Response payload: {domain, name, path, keywords, metadata}
    """
    WriteBlackboard: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Blackboard Operations (Flat Memory)
    =========================================

    Write arbitrary data to the blackboard, return UUID
    Request payload: {tenant_id, scope_path, content, metadata?, ttl_seconds?, created_by?}
    Response payload: {id, scope_path, created_at}
    """
    ReadBlackboard: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Read one or more records by UUID(s) — STRICTLY BATCHED
    Request payload: {ids: [UUID, ...]}
    Response payload: {records: [{id, content, metadata, scope_path, created_at}]}
    """
    RecordSynapse: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    BrainSynapse Operations (Flat Memory Phase B)
    =========================================

    Record a BrainSynapse learning trace.
    Request payload: {tenant_id?, agent_id, action_type, action_data?, action_data_ref?,
      thought_trace_ref?, content_hash?, graph_name?, graph_run_id?, node_id?, node_name?,
      node_role?, scope_path?, context_summary?, client_id?, fault_class?, status?,
      q_action?, q_hypothesis?, q_relevance?, metadata?}
    Response payload: {id, agent_id, action_type, node_role, status, q_action,
      q_hypothesis, q_relevance, q_composite, scope_path, metadata, created_at, updated_at}
    """
    QuerySynapses: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Query BrainSynapses, ranked by q_composite and bounded by limit.
    Request payload: {tenant_id?, action_type?, agent_id?, node_role?, status?,
      scope_path?, min_q?, limit?}
    Response payload stream: one ContextUnit per Synapse row, same shape as RecordSynapse's
      response plus {graph_name, graph_run_id, node_id, node_name, action_data,
      action_data_ref, context_summary, thought_trace_ref, content_hash, fault_class}
    """
    UpdateSynapseQ: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Update Q-values/fault/status on one tenant-owned Synapse after an outcome/review.
    Request payload: {synapse_id, q_action?, q_hypothesis?, q_relevance?, fault_class?,
      status?, metadata_patch?}
    Response payload: {id, q_action, q_hypothesis, q_relevance, q_composite, updated_at}
    """
    MatchDuckDB: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    DuckDB Operations
    =========================================

    Execute high-speed DuckDB string/fuzzy matching on Parquet files
    Request payload: {tenant_id, unmatched_uri, canonical_uri}
    Response payload: {duckdb_matches: [...], duckdb_leftovers_count: int}
    """
    ListTenants: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Admin RPCs (WS-8) — require admin:read
    Cross-tenant observability owned by Brain.
    Replaces View brain_db RLS bypass (S8).
    =========================================

    List all tenants the caller may administer.
    Requires admin:read.
    Token admin:all → all tenants; else intersection with allowed_tenants.
    Request payload: {}
    Response payload: {tenants: [{id, label?, trace_count?}]}
    """
    AdminSearchTraces: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Cross-tenant trace search.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, service?, agent_id?, status?, hours?, limit?, offset?}
    Response payload: {traces: [...], total: int}
    """
    AdminGetTraceDetails: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get full details for a single trace (cross-tenant, admin-only).
    Requires admin:read.
    Request payload: {trace_id}
    Response payload: same shape as GetTraces row
    """
    AdminGetSystemAnalytics: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Cross-tenant system analytics aggregates.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {hours?, tenant_id?}
    Response payload: {analytics: {...}}
    """
    AdminGetMemoryLayerStats: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Cross-tenant memory layer stats (episodes, knowledge node counts).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {layer?, tenant_id?}
    Response payload: {layer_stats: {...}}
    """
    AdminGetFilterOptions: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Distinct filter values from agent_traces (for admin UI dropdowns).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?}
    Response payload: {filter_options: {agent_ids, tenant_ids, graph_names, user_ids}}
    """
    AdminGetSessionTraces: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Fetch all traces for a given session_id (cross-tenant, admin-only).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {session_id, tenant_id?}
    Response payload: {traces: [...]}
    """
    AdminGetRelatedEpisodes: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Fetch episodic_events related to a trace by trace_id (cross-tenant).
    Requires admin:read.
    Tenant scope is resolved from the trace's own tenant_id (by-id lookup).
    Request payload: {trace_id}
    Response payload: {episodes: [...]}
    """
    AdminSearchEpisodes: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Cross-tenant episodic event search with pagination.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, user_id?, session_id?, hours?, limit?, offset?}
    Response payload: {events: [...], total: int}
    """
    AdminGetCells: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """List cells with optional tenant/kind filter (cross-tenant).
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, kind?, limit?}
    Response payload: {nodes: [...]}
    """
    AdminGetAnalyticsSummary: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Rich analytics summary with per-hour breakdown, token costs, tool usage.
    Requires admin:read.
    tenant_id is optional only when token has admin:all; otherwise required.
    Request payload: {tenant_id?, hours?}
    Response payload: {analytics: {...}}
    """

class BrainServiceServicer(metaclass=_abc_1.ABCMeta):
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    @_abc_1.abstractmethod
    def Search(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Semantic/Hybrid search
        Request payload: {tenant_id, query_text, limit?, source_types?}
        Response payload: {id, content, score, source_type, metadata}
        """

    @_abc_1.abstractmethod
    def GraphSearch(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Graph Traversal
        Request payload: {tenant_id, entrypoint_ids, max_hops?, allowed_relations?}
        Response payload: {nodes: [...], edges: [...]}
        """

    @_abc_1.abstractmethod
    def CreateKGRelation(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Create Knowledge Graph relation
        Request payload: {tenant_id, source_type, source_id, relation, target_type, target_id}
        Response payload: {success}
        """

    @_abc_1.abstractmethod
    def Upsert(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Upsert content (generic)
        Request payload: {tenant_id, content, source_type, metadata?}
        Response payload: {id, success}
        """

    @_abc_1.abstractmethod
    def QueryMemory(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Query memory (hybrid search with provenance)
        Request payload: {tenant_id, content, filters?}
        Response payload: {content, metadata, score}
        """

    @_abc_1.abstractmethod
    def AddEpisode(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Episodic & Entity Memory
        =========================================

        Add conversation episode
        Request payload: {user_id, tenant_id, session_id?, content, metadata?}
        """

    @_abc_1.abstractmethod
    def GetRecentEpisodes(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Get recent episodes for a user
        Request payload: {tenant_id, user_id, limit?}
        Response payload: {id, content, metadata, created_at}
        """

    @_abc_1.abstractmethod
    def UpsertFact(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Upsert user fact
        Request payload: {user_id, tenant_id, key, value, confidence?, source_id?}
        """

    @_abc_1.abstractmethod
    def GetUserFacts(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Get all facts for a user
        Request payload: {tenant_id, user_id}
        Response payload: {fact_key, fact_value, confidence, updated_at}
        """

    @_abc_1.abstractmethod
    def GetEpisodeStats(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Get episode count and date range for a tenant
        Request payload: {tenant_id}
        Response payload: {total, oldest, newest, tenant_id}
        """

    @_abc_1.abstractmethod
    def RetentionCleanup(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Delete old episodes for a tenant, optionally restricted to explicit IDs
        Request payload: {tenant_id, older_than_days, episode_ids?}
        Response payload: {deleted_count}
        """

    @_abc_1.abstractmethod
    def LogTrace(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Agent Traces
        =========================================

        Log an agent execution trace
        Request payload: {tenant_id, agent_id, session_id?, graph_name?,
          tool_calls?, token_usage?, timing_ms?, security_flags?, metadata?}
        Response payload: {id, success}
        """

    @_abc_1.abstractmethod
    def GetTraces(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Get traces (admin/observability)
        Request payload: {tenant_id, agent_id?, session_id?, limit?, since?}
        Response payload: {id, agent_id, graph_name, tool_calls, token_usage,
          timing_ms, security_flags, metadata, created_at}
        """

    @_abc_1.abstractmethod
    def UpsertTaxonomy(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Taxonomy Operations
        =========================================

        Upsert taxonomy entry
        Request payload: {tenant_id, domain, name, path, keywords?, metadata?}
        """

    @_abc_1.abstractmethod
    def GetTaxonomy(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Get taxonomy entries
        Request payload: {tenant_id, domain?}
        Response payload: {domain, name, path, keywords, metadata}
        """

    @_abc_1.abstractmethod
    def WriteBlackboard(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Blackboard Operations (Flat Memory)
        =========================================

        Write arbitrary data to the blackboard, return UUID
        Request payload: {tenant_id, scope_path, content, metadata?, ttl_seconds?, created_by?}
        Response payload: {id, scope_path, created_at}
        """

    @_abc_1.abstractmethod
    def ReadBlackboard(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Read one or more records by UUID(s) — STRICTLY BATCHED
        Request payload: {ids: [UUID, ...]}
        Response payload: {records: [{id, content, metadata, scope_path, created_at}]}
        """

    @_abc_1.abstractmethod
    def RecordSynapse(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        BrainSynapse Operations (Flat Memory Phase B)
        =========================================

        Record a BrainSynapse learning trace.
        Request payload: {tenant_id?, agent_id, action_type, action_data?, action_data_ref?,
          thought_trace_ref?, content_hash?, graph_name?, graph_run_id?, node_id?, node_name?,
          node_role?, scope_path?, context_summary?, client_id?, fault_class?, status?,
          q_action?, q_hypothesis?, q_relevance?, metadata?}
        Response payload: {id, agent_id, action_type, node_role, status, q_action,
          q_hypothesis, q_relevance, q_composite, scope_path, metadata, created_at, updated_at}
        """

    @_abc_1.abstractmethod
    def QuerySynapses(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Query BrainSynapses, ranked by q_composite and bounded by limit.
        Request payload: {tenant_id?, action_type?, agent_id?, node_role?, status?,
          scope_path?, min_q?, limit?}
        Response payload stream: one ContextUnit per Synapse row, same shape as RecordSynapse's
          response plus {graph_name, graph_run_id, node_id, node_name, action_data,
          action_data_ref, context_summary, thought_trace_ref, content_hash, fault_class}
        """

    @_abc_1.abstractmethod
    def UpdateSynapseQ(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Update Q-values/fault/status on one tenant-owned Synapse after an outcome/review.
        Request payload: {synapse_id, q_action?, q_hypothesis?, q_relevance?, fault_class?,
          status?, metadata_patch?}
        Response payload: {id, q_action, q_hypothesis, q_relevance, q_composite, updated_at}
        """

    @_abc_1.abstractmethod
    def MatchDuckDB(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        DuckDB Operations
        =========================================

        Execute high-speed DuckDB string/fuzzy matching on Parquet files
        Request payload: {tenant_id, unmatched_uri, canonical_uri}
        Response payload: {duckdb_matches: [...], duckdb_leftovers_count: int}
        """

    @_abc_1.abstractmethod
    def ListTenants(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Admin RPCs (WS-8) — require admin:read
        Cross-tenant observability owned by Brain.
        Replaces View brain_db RLS bypass (S8).
        =========================================

        List all tenants the caller may administer.
        Requires admin:read.
        Token admin:all → all tenants; else intersection with allowed_tenants.
        Request payload: {}
        Response payload: {tenants: [{id, label?, trace_count?}]}
        """

    @_abc_1.abstractmethod
    def AdminSearchTraces(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Cross-tenant trace search.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, service?, agent_id?, status?, hours?, limit?, offset?}
        Response payload: {traces: [...], total: int}
        """

    @_abc_1.abstractmethod
    def AdminGetTraceDetails(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Get full details for a single trace (cross-tenant, admin-only).
        Requires admin:read.
        Request payload: {trace_id}
        Response payload: same shape as GetTraces row
        """

    @_abc_1.abstractmethod
    def AdminGetSystemAnalytics(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Cross-tenant system analytics aggregates.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {hours?, tenant_id?}
        Response payload: {analytics: {...}}
        """

    @_abc_1.abstractmethod
    def AdminGetMemoryLayerStats(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Cross-tenant memory layer stats (episodes, knowledge node counts).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {layer?, tenant_id?}
        Response payload: {layer_stats: {...}}
        """

    @_abc_1.abstractmethod
    def AdminGetFilterOptions(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Distinct filter values from agent_traces (for admin UI dropdowns).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?}
        Response payload: {filter_options: {agent_ids, tenant_ids, graph_names, user_ids}}
        """

    @_abc_1.abstractmethod
    def AdminGetSessionTraces(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Fetch all traces for a given session_id (cross-tenant, admin-only).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {session_id, tenant_id?}
        Response payload: {traces: [...]}
        """

    @_abc_1.abstractmethod
    def AdminGetRelatedEpisodes(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Fetch episodic_events related to a trace by trace_id (cross-tenant).
        Requires admin:read.
        Tenant scope is resolved from the trace's own tenant_id (by-id lookup).
        Request payload: {trace_id}
        Response payload: {episodes: [...]}
        """

    @_abc_1.abstractmethod
    def AdminSearchEpisodes(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Cross-tenant episodic event search with pagination.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, user_id?, session_id?, hours?, limit?, offset?}
        Response payload: {events: [...], total: int}
        """

    @_abc_1.abstractmethod
    def AdminGetCells(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """List cells with optional tenant/kind filter (cross-tenant).
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, kind?, limit?}
        Response payload: {nodes: [...]}
        """

    @_abc_1.abstractmethod
    def AdminGetAnalyticsSummary(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Rich analytics summary with per-hour breakdown, token costs, tool usage.
        Requires admin:read.
        tenant_id is optional only when token has admin:all; otherwise required.
        Request payload: {tenant_id?, hours?}
        Response payload: {analytics: {...}}
        """

def add_BrainServiceServicer_to_server(
    servicer: BrainServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]
) -> None: ...
