"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc as _abc_1
import sys
import typing as _typing
from collections import abc as _abc

import grpc as _grpc
from grpc import aio as _aio

from . import contextunit_pb2 as _contextunit_pb2

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...
class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class BrainServiceStub:
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> BrainServiceAsyncStub: ...
    Search: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Semantic/Hybrid search
    Request payload: {tenant_id, query_text, limit?, source_types?}
    Response payload: {id, content, score, source_type, metadata}
    """
    GraphSearch: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Graph Traversal
    Request payload: {tenant_id, entrypoint_ids, max_hops?, allowed_relations?}
    Response payload: {nodes: [...], edges: [...]}
    """
    CreateKGRelation: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Create Knowledge Graph relation
    Request payload: {tenant_id, source_type, source_id, relation, target_type, target_id}
    Response payload: {success}
    """
    Upsert: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Upsert content (generic)
    Request payload: {tenant_id, content, source_type, metadata?}
    Response payload: {id, success}
    """
    QueryMemory: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Query memory (hybrid search with provenance)
    Request payload: {tenant_id, content, filters?}
    Response payload: {content, metadata, score}
    """
    AddEpisode: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Episodic & Entity Memory
    =========================================

    Add conversation episode
    Request payload: {user_id, tenant_id, session_id?, content, metadata?}
    """
    GetRecentEpisodes: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get recent episodes for a user
    Request payload: {tenant_id, user_id, limit?}
    Response payload: {id, content, metadata, created_at}
    """
    UpsertFact: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Upsert user fact
    Request payload: {user_id, tenant_id, key, value, confidence?, source_id?}
    """
    GetUserFacts: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get all facts for a user
    Request payload: {tenant_id, user_id}
    Response payload: {fact_key, fact_value, confidence, updated_at}
    """
    GetEpisodeStats: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get episode count and date range for a tenant
    Request payload: {tenant_id}
    Response payload: {total, oldest, newest, tenant_id}
    """
    RetentionCleanup: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Delete old episodes for a tenant, optionally restricted to explicit IDs
    Request payload: {tenant_id, older_than_days, episode_ids?}
    Response payload: {deleted_count}
    """
    LogTrace: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Agent Traces
    =========================================

    Log an agent execution trace
    Request payload: {tenant_id, agent_id, session_id?, graph_name?,
      tool_calls?, token_usage?, timing_ms?, security_flags?, metadata?}
    Response payload: {id, success}
    """
    GetTraces: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get traces (admin/observability)
    Request payload: {tenant_id, agent_id?, session_id?, limit?, since?}
    Response payload: {id, agent_id, graph_name, tool_calls, token_usage,
      timing_ms, security_flags, metadata, created_at}
    """
    UpsertTaxonomy: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Taxonomy Operations
    =========================================

    Upsert taxonomy entry
    Request payload: {tenant_id, domain, name, path, keywords?, metadata?}
    """
    GetTaxonomy: _grpc.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get taxonomy entries
    Request payload: {tenant_id, domain?}
    Response payload: {domain, name, path, keywords, metadata}
    """
    WriteBlackboard: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    Blackboard Operations (Flat Memory)
    =========================================

    Write arbitrary data to the blackboard, return UUID
    Request payload: {tenant_id, scope_path, content, metadata?, ttl_seconds?, created_by?}
    Response payload: {id, scope_path, created_at}
    """
    ReadBlackboard: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Read one or more records by UUID(s) — STRICTLY BATCHED
    Request payload: {ids: [UUID, ...]}
    Response payload: {records: [{id, content, metadata, scope_path, created_at}]}
    """
    MatchDuckDB: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=========================================
    DuckDB Operations
    =========================================

    Execute high-speed DuckDB string/fuzzy matching on Parquet files
    Request payload: {tenant_id, unmatched_uri, canonical_uri}
    Response payload: {duckdb_matches: [...], duckdb_leftovers_count: int}
    """

@_typing.type_check_only
class BrainServiceAsyncStub(BrainServiceStub):
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Search: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Semantic/Hybrid search
    Request payload: {tenant_id, query_text, limit?, source_types?}
    Response payload: {id, content, score, source_type, metadata}
    """
    GraphSearch: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Graph Traversal
    Request payload: {tenant_id, entrypoint_ids, max_hops?, allowed_relations?}
    Response payload: {nodes: [...], edges: [...]}
    """
    CreateKGRelation: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Create Knowledge Graph relation
    Request payload: {tenant_id, source_type, source_id, relation, target_type, target_id}
    Response payload: {success}
    """
    Upsert: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Upsert content (generic)
    Request payload: {tenant_id, content, source_type, metadata?}
    Response payload: {id, success}
    """
    QueryMemory: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Query memory (hybrid search with provenance)
    Request payload: {tenant_id, content, filters?}
    Response payload: {content, metadata, score}
    """
    AddEpisode: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Episodic & Entity Memory
    =========================================

    Add conversation episode
    Request payload: {user_id, tenant_id, session_id?, content, metadata?}
    """
    GetRecentEpisodes: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get recent episodes for a user
    Request payload: {tenant_id, user_id, limit?}
    Response payload: {id, content, metadata, created_at}
    """
    UpsertFact: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Upsert user fact
    Request payload: {user_id, tenant_id, key, value, confidence?, source_id?}
    """
    GetUserFacts: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get all facts for a user
    Request payload: {tenant_id, user_id}
    Response payload: {fact_key, fact_value, confidence, updated_at}
    """
    GetEpisodeStats: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get episode count and date range for a tenant
    Request payload: {tenant_id}
    Response payload: {total, oldest, newest, tenant_id}
    """
    RetentionCleanup: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Delete old episodes for a tenant, optionally restricted to explicit IDs
    Request payload: {tenant_id, older_than_days, episode_ids?}
    Response payload: {deleted_count}
    """
    LogTrace: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Agent Traces
    =========================================

    Log an agent execution trace
    Request payload: {tenant_id, agent_id, session_id?, graph_name?,
      tool_calls?, token_usage?, timing_ms?, security_flags?, metadata?}
    Response payload: {id, success}
    """
    GetTraces: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get traces (admin/observability)
    Request payload: {tenant_id, agent_id?, session_id?, limit?, since?}
    Response payload: {id, agent_id, graph_name, tool_calls, token_usage,
      timing_ms, security_flags, metadata, created_at}
    """
    UpsertTaxonomy: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Taxonomy Operations
    =========================================

    Upsert taxonomy entry
    Request payload: {tenant_id, domain, name, path, keywords?, metadata?}
    """
    GetTaxonomy: _aio.UnaryStreamMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get taxonomy entries
    Request payload: {tenant_id, domain?}
    Response payload: {domain, name, path, keywords, metadata}
    """
    WriteBlackboard: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    Blackboard Operations (Flat Memory)
    =========================================

    Write arbitrary data to the blackboard, return UUID
    Request payload: {tenant_id, scope_path, content, metadata?, ttl_seconds?, created_by?}
    Response payload: {id, scope_path, created_at}
    """
    ReadBlackboard: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Read one or more records by UUID(s) — STRICTLY BATCHED
    Request payload: {ids: [UUID, ...]}
    Response payload: {records: [{id, content, metadata, scope_path, created_at}]}
    """
    MatchDuckDB: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=========================================
    DuckDB Operations
    =========================================

    Execute high-speed DuckDB string/fuzzy matching on Parquet files
    Request payload: {tenant_id, unmatched_uri, canonical_uri}
    Response payload: {duckdb_matches: [...], duckdb_leftovers_count: int}
    """

class BrainServiceServicer(metaclass=_abc_1.ABCMeta):
    """=====================================================
    Brain Service - Universal Knowledge Operations
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.

    SPOT: Tenant identity is carried by ``ContextToken`` metadata — never
    by in-band payload. Legacy ``tenant_id`` fields in payloads are
    accepted for backward compatibility but MUST be consistent with the
    token's ``allowed_tenants`` or the request is rejected with
    PERMISSION_DENIED. New callers SHOULD omit ``tenant_id`` from payload
    and rely on the token.
    =====================================================

    =========================================
    Core Knowledge Operations
    =========================================
    """

    @_abc_1.abstractmethod
    def Search(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Semantic/Hybrid search
        Request payload: {tenant_id, query_text, limit?, source_types?}
        Response payload: {id, content, score, source_type, metadata}
        """

    @_abc_1.abstractmethod
    def GraphSearch(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Graph Traversal
        Request payload: {tenant_id, entrypoint_ids, max_hops?, allowed_relations?}
        Response payload: {nodes: [...], edges: [...]}
        """

    @_abc_1.abstractmethod
    def CreateKGRelation(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Create Knowledge Graph relation
        Request payload: {tenant_id, source_type, source_id, relation, target_type, target_id}
        Response payload: {success}
        """

    @_abc_1.abstractmethod
    def Upsert(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Upsert content (generic)
        Request payload: {tenant_id, content, source_type, metadata?}
        Response payload: {id, success}
        """

    @_abc_1.abstractmethod
    def QueryMemory(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Query memory (hybrid search with provenance)
        Request payload: {tenant_id, content, filters?}
        Response payload: {content, metadata, score}
        """

    @_abc_1.abstractmethod
    def AddEpisode(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Episodic & Entity Memory
        =========================================

        Add conversation episode
        Request payload: {user_id, tenant_id, session_id?, content, metadata?}
        """

    @_abc_1.abstractmethod
    def GetRecentEpisodes(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Get recent episodes for a user
        Request payload: {tenant_id, user_id, limit?}
        Response payload: {id, content, metadata, created_at}
        """

    @_abc_1.abstractmethod
    def UpsertFact(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Upsert user fact
        Request payload: {user_id, tenant_id, key, value, confidence?, source_id?}
        """

    @_abc_1.abstractmethod
    def GetUserFacts(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Get all facts for a user
        Request payload: {tenant_id, user_id}
        Response payload: {fact_key, fact_value, confidence, updated_at}
        """

    @_abc_1.abstractmethod
    def GetEpisodeStats(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Get episode count and date range for a tenant
        Request payload: {tenant_id}
        Response payload: {total, oldest, newest, tenant_id}
        """

    @_abc_1.abstractmethod
    def RetentionCleanup(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Delete old episodes for a tenant, optionally restricted to explicit IDs
        Request payload: {tenant_id, older_than_days, episode_ids?}
        Response payload: {deleted_count}
        """

    @_abc_1.abstractmethod
    def LogTrace(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Agent Traces
        =========================================

        Log an agent execution trace
        Request payload: {tenant_id, agent_id, session_id?, graph_name?,
          tool_calls?, token_usage?, timing_ms?, security_flags?, metadata?}
        Response payload: {id, success}
        """

    @_abc_1.abstractmethod
    def GetTraces(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Get traces (admin/observability)
        Request payload: {tenant_id, agent_id?, session_id?, limit?, since?}
        Response payload: {id, agent_id, graph_name, tool_calls, token_usage,
          timing_ms, security_flags, metadata, created_at}
        """

    @_abc_1.abstractmethod
    def UpsertTaxonomy(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Taxonomy Operations
        =========================================

        Upsert taxonomy entry
        Request payload: {tenant_id, domain, name, path, keywords?, metadata?}
        """

    @_abc_1.abstractmethod
    def GetTaxonomy(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_contextunit_pb2.ContextUnit], _abc.AsyncIterator[_contextunit_pb2.ContextUnit]]:
        """Get taxonomy entries
        Request payload: {tenant_id, domain?}
        Response payload: {domain, name, path, keywords, metadata}
        """

    @_abc_1.abstractmethod
    def WriteBlackboard(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        Blackboard Operations (Flat Memory)
        =========================================

        Write arbitrary data to the blackboard, return UUID
        Request payload: {tenant_id, scope_path, content, metadata?, ttl_seconds?, created_by?}
        Response payload: {id, scope_path, created_at}
        """

    @_abc_1.abstractmethod
    def ReadBlackboard(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Read one or more records by UUID(s) — STRICTLY BATCHED
        Request payload: {ids: [UUID, ...]}
        Response payload: {records: [{id, content, metadata, scope_path, created_at}]}
        """

    @_abc_1.abstractmethod
    def MatchDuckDB(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=========================================
        DuckDB Operations
        =========================================

        Execute high-speed DuckDB string/fuzzy matching on Parquet files
        Request payload: {tenant_id, unmatched_uri, canonical_uri}
        Response payload: {duckdb_matches: [...], duckdb_leftovers_count: int}
        """

def add_BrainServiceServicer_to_server(
    servicer: BrainServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]
) -> None: ...
