"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper

if sys.version_info >= (3, 11):
    from typing import Never as _Never
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import Never as _Never
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Modality:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ModalityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Modality.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TEXT: _Modality.ValueType  # 0
    AUDIO: _Modality.ValueType  # 1
    SPATIAL: _Modality.ValueType  # 2
    IMAGE: _Modality.ValueType  # 3

class Modality(_Modality, metaclass=_ModalityEnumTypeWrapper):
    """=====================================================
    ContextUnit - The Universal Data Contract
    =====================================================
    Every gRPC call in ContextUnity uses ContextUnit.
    Domain-specific data goes in the payload field.
    =====================================================

    Modality of the unit payload
    """

TEXT: Modality.ValueType  # 0
AUDIO: Modality.ValueType  # 1
SPATIAL: Modality.ValueType  # 2
IMAGE: Modality.ValueType  # 3
Global___Modality: _TypeAlias = Modality  # noqa: Y015

@_typing.final
class UnitMetrics(_message.Message):
    """Metrics for observability"""

    DESCRIPTOR: _descriptor.Descriptor

    LATENCY_MS_FIELD_NUMBER: _builtins.int
    COST_USD_FIELD_NUMBER: _builtins.int
    TOKENS_USED_FIELD_NUMBER: _builtins.int
    COST_LIMIT_USD_FIELD_NUMBER: _builtins.int
    latency_ms: _builtins.int
    cost_usd: _builtins.float
    tokens_used: _builtins.int
    cost_limit_usd: _builtins.float
    """Max budget for this unit lifecycle"""
    def __init__(
        self,
        *,
        latency_ms: _builtins.int = ...,
        cost_usd: _builtins.float = ...,
        tokens_used: _builtins.int = ...,
        cost_limit_usd: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "cost_limit_usd",
        b"cost_limit_usd",
        "cost_usd",
        b"cost_usd",
        "latency_ms",
        b"latency_ms",
        "tokens_used",
        b"tokens_used",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnitMetrics: _TypeAlias = UnitMetrics  # noqa: Y015

@_typing.final
class SecurityScopes(_message.Message):
    """Security scopes for capability-based access control"""

    DESCRIPTOR: _descriptor.Descriptor

    READ_FIELD_NUMBER: _builtins.int
    WRITE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def read(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """E.g. ["catalog:read", "price:historical"]"""

    @_builtins.property
    def write(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """E.g. ["product:patch", "stock:update"]"""

    def __init__(
        self,
        *,
        read: _abc.Iterable[_builtins.str] | None = ...,
        write: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["read", b"read", "write", b"write"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SecurityScopes: _TypeAlias = SecurityScopes  # noqa: Y015

@_typing.final
class CotStep(_message.Message):
    """Chain of Thought step"""

    DESCRIPTOR: _descriptor.Descriptor

    AGENT_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    agent: _builtins.str
    action: _builtins.str
    status: _builtins.str
    """"success", "failure", "pending" """
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        agent: _builtins.str = ...,
        action: _builtins.str = ...,
        status: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "action", b"action", "agent", b"agent", "status", b"status", "timestamp", b"timestamp"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CotStep: _TypeAlias = CotStep  # noqa: Y015

@_typing.final
class ContextUnit(_message.Message):
    """The core atom of ContextUnity - Universal Data Contract"""

    DESCRIPTOR: _descriptor.Descriptor

    UNIT_ID_FIELD_NUMBER: _builtins.int
    TRACE_ID_FIELD_NUMBER: _builtins.int
    PARENT_UNIT_ID_FIELD_NUMBER: _builtins.int
    MODALITY_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    CHAIN_OF_THOUGHT_FIELD_NUMBER: _builtins.int
    METRICS_FIELD_NUMBER: _builtins.int
    SECURITY_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    PROVENANCE_FIELD_NUMBER: _builtins.int
    unit_id: _builtins.str
    """UUIDv4"""
    trace_id: _builtins.str
    """UUIDv4 cross-service trace"""
    parent_unit_id: _builtins.str
    """Optional parent reference"""
    modality: Global___Modality.ValueType
    @_builtins.property
    def payload(self) -> _struct_pb2.Struct:
        """The actual data (domain-specific)"""

    @_builtins.property
    def chain_of_thought(self) -> _containers.RepeatedCompositeFieldContainer[Global___CotStep]: ...
    @_builtins.property
    def metrics(self) -> Global___UnitMetrics: ...
    @_builtins.property
    def security(self) -> Global___SecurityScopes: ...
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def provenance(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Data journey labels across services/tools"""

    def __init__(
        self,
        *,
        unit_id: _builtins.str = ...,
        trace_id: _builtins.str = ...,
        parent_unit_id: _builtins.str = ...,
        modality: Global___Modality.ValueType = ...,
        payload: _struct_pb2.Struct | None = ...,
        chain_of_thought: _abc.Iterable[Global___CotStep] | None = ...,
        metrics: Global___UnitMetrics | None = ...,
        security: Global___SecurityScopes | None = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        provenance: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "created_at", b"created_at", "metrics", b"metrics", "payload", b"payload", "security", b"security"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "chain_of_thought",
        b"chain_of_thought",
        "created_at",
        b"created_at",
        "metrics",
        b"metrics",
        "modality",
        b"modality",
        "parent_unit_id",
        b"parent_unit_id",
        "payload",
        b"payload",
        "provenance",
        b"provenance",
        "security",
        b"security",
        "trace_id",
        b"trace_id",
        "unit_id",
        b"unit_id",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ContextUnit: _TypeAlias = ContextUnit  # noqa: Y015
