# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: router.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "router.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x0crouter.proto\x12\x13\x63ontextunity.router\x1a\x11\x63ontextunit.proto2\x89\x04\n\rRouterService\x12N\n\x0c\x45xecuteAgent\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12O\n\x0bStreamAgent\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit0\x01\x12S\n\x11\x45xecuteDispatcher\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12T\n\x10StreamDispatcher\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit0\x01\x12R\n\x10RegisterManifest\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12X\n\x12ToolExecutorStream\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit(\x01\x30\x01\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "router_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ROUTERSERVICE"]._serialized_start = 57
    _globals["_ROUTERSERVICE"]._serialized_end = 578
# @@protoc_insertion_point(module_scope)
