# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import contextunit_pb2 as contextunit__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in router_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RouterServiceStub(object):
    """=====================================================
    Router Service - AI Agent Orchestration
    =====================================================
    All methods use ContextUnit as input/output.
    Agent identification and input is passed via payload.
    =====================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteAgent = channel.unary_unary(
            "/contextunity.router.RouterService/ExecuteAgent",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.StreamAgent = channel.unary_stream(
            "/contextunity.router.RouterService/StreamAgent",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.ExecuteDispatcher = channel.unary_unary(
            "/contextunity.router.RouterService/ExecuteDispatcher",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.StreamDispatcher = channel.unary_stream(
            "/contextunity.router.RouterService/StreamDispatcher",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.RegisterManifest = channel.unary_unary(
            "/contextunity.router.RouterService/RegisterManifest",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.ToolExecutorStream = channel.stream_stream(
            "/contextunity.router.RouterService/ToolExecutorStream",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.ExecuteNode = channel.unary_unary(
            "/contextunity.router.RouterService/ExecuteNode",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.IntrospectRegistrations = channel.unary_unary(
            "/contextunity.router.RouterService/IntrospectRegistrations",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )


class RouterServiceServicer(object):
    """=====================================================
    Router Service - AI Agent Orchestration
    =====================================================
    All methods use ContextUnit as input/output.
    Agent identification and input is passed via payload.
    =====================================================

    """

    def ExecuteAgent(self, request, context):
        """Execute a single turn of an agent
        Request payload: {agent_id, input, config?}
        Tenant/user identity is derived from ContextToken (SPOT).
        Response payload: {output, wall_ms?, langfuse_trace_id?, langfuse_trace_url?}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamAgent(self, request, context):
        """Stream agent execution (for UI with real-time output)
        Request payload: {agent_id, input, config?}
        Tenant/user identity is derived from ContextToken (SPOT).
        Response payload: streaming ContextUnit events (progress/result/etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteDispatcher(self, request, context):
        """=========================================
        Dispatcher Agent - Always-Active Agent
        =========================================

        Execute dispatcher agent (always-active agent with all tools)
        Request payload: {messages: [{role, content}], session_id?, platform?, max_iterations?}
        Tenant/user identity is derived from ContextToken (SPOT).
        Response payload: {messages: [...], session_id, metadata: {...}}
        Security: Uses SecurityScopes from ContextUnit for access control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamDispatcher(self, request, context):
        """Stream dispatcher agent execution
        Request payload: {messages: [{role, content}], session_id?, platform?, max_iterations?}
        Tenant/user identity is derived from ContextToken (SPOT).
        Response payload: {event_type, data: {...}} (streaming events)
        Security: Uses SecurityScopes from ContextUnit for access control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RegisterManifest(self, request, context):
        """=========================================
        Project Tool & Graph Registration
        =========================================

        Deregister project tools and graph (on shutdown).
        Request payload: {project_id: "contextmed"}
        Response payload: {deregistered: [...], status: "ok"}

        =========================================
        Dynamic Project Manifest Registration
        =========================================

        Register an entire ContextUnity project manifest at once via dynamic gRPC push.
        Replaces RegisterTools by acting on the Canonical Project Manifest directly.

        Security: Requires "tools:register" write scope in ContextUnit.

        Request payload: {
        bundle: {... compiled dictionary from ArtifactGenerator ...},
        hash: "a1b2c3d4..." // Optional: Used for idempotent validation against Redis cache
        }

        Response payload: {registered_tools: [...], graph: "contextmed", status: "ok", hash_matched: true/false}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ToolExecutorStream(self, request_iterator, context):
        """=========================================
        Tool Executor Stream (Bidi Callback)
        =========================================

        Bidirectional stream for project-side tool execution.
        Project connects once and acts as remote executor for its tools.
        Uses existing gRPC connection — no new ports needed.

        Flow:
        1. Project → Router: {"action": "ready", "project_id": "nszu",
        "tools": ["execute_medical_sql"]}
        2. Router → Project: {"action": "execute", "tool": "execute_medical_sql",
        "request_id": "abc", "args": {"sql": "SELECT ..."}}
        3. Project → Router: {"action": "result", "request_id": "abc",
        "columns": [...], "rows": [...], "row_count": N}
        4. On error:
        Project → Router: {"action": "error", "request_id": "abc",
        "error": "timeout"}

        Security: Requires ContextToken with "tools:register" permission.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteNode(self, request, context):
        """=========================================
        Graph Compiler — Node Execution (Phase 2)
        =========================================

        Execute a single compiled graph node by name.
        Enables Worker workflows to invoke Router nodes directly
        (e.g., synthesis workflow calling an LLM node for fact extraction).

        Request payload: {
        graph_name: string,         // Compiled graph identifier
        node_name: string,          // Node to execute within the graph
        state: {key: value, ...},   // Node input state
        config_overrides?: {...}    // Optional per-call config
        }
        Tenant/user identity is derived from ContextToken (SPOT).

        Response payload: {
        output: {key: value, ...},  // Node execution output
        node_name: string,
        execution_ms: int
        }

        Security: Requires ContextToken with "router:execute_node" permission.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IntrospectRegistrations(self, request, context):
        """=========================================
        Introspection — Registered Manifest Query
        =========================================

        Inspect registered project manifests (sanitized, read-only).
        Used by TUI, admin dashboards, and observability tooling.

        Request payload: {
        project_id?: string  // Optional — omit to list all visible projects
        }

        Response payload: {
        projects: [{
        project_id, owner_tenant, security_mode,
        services, tools, graphs, policy
        }]
        }

        Secrets are NEVER included in the response (sanitized server-side).
        Security: Requires "router:introspect" permission.
        In CU_LOCAL_MODE, HMAC tokens are accepted even when Shield is primary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecuteAgent": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteAgent,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "StreamAgent": grpc.unary_stream_rpc_method_handler(
            servicer.StreamAgent,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "ExecuteDispatcher": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteDispatcher,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "StreamDispatcher": grpc.unary_stream_rpc_method_handler(
            servicer.StreamDispatcher,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "RegisterManifest": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterManifest,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "ToolExecutorStream": grpc.stream_stream_rpc_method_handler(
            servicer.ToolExecutorStream,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "ExecuteNode": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteNode,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "IntrospectRegistrations": grpc.unary_unary_rpc_method_handler(
            servicer.IntrospectRegistrations,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("contextunity.router.RouterService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("contextunity.router.RouterService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RouterService(object):
    """=====================================================
    Router Service - AI Agent Orchestration
    =====================================================
    All methods use ContextUnit as input/output.
    Agent identification and input is passed via payload.
    =====================================================

    """

    @staticmethod
    def ExecuteAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.router.RouterService/ExecuteAgent",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextunity.router.RouterService/StreamAgent",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteDispatcher(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.router.RouterService/ExecuteDispatcher",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamDispatcher(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextunity.router.RouterService/StreamDispatcher",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RegisterManifest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.router.RouterService/RegisterManifest",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ToolExecutorStream(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/contextunity.router.RouterService/ToolExecutorStream",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.router.RouterService/ExecuteNode",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def IntrospectRegistrations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.router.RouterService/IntrospectRegistrations",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
