# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shield.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "shield.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x0cshield.proto\x12\x13\x63ontextunity.shield\x1a\x11\x63ontextunit.proto2\xa6\x0b\n\rShieldService\x12\x46\n\x04Scan\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12P\n\x0e\x45valuatePolicy\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12Q\n\x0f\x43heckCompliance\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12M\n\x0bRecordAudit\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12K\n\tMintToken\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12M\n\x0bVerifyToken\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12M\n\x0bRevokeToken\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12J\n\x08GetStats\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12K\n\tGetSecret\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12K\n\tPutSecret\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12M\n\x0bListSecrets\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12N\n\x0cRotateSecret\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12I\n\x07\x45ncrypt\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12I\n\x07\x44\x65\x63rypt\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12S\n\x11SyncProjectPolicy\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12S\n\x11IssueSessionToken\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12U\n\x13GetProjectPublicKey\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnit\x12R\n\x10RotateProjectKey\x12\x1e.contextunity.core.ContextUnit\x1a\x1e.contextunity.core.ContextUnitb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "shield_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SHIELDSERVICE"]._serialized_start = 57
    _globals["_SHIELDSERVICE"]._serialized_end = 1503
# @@protoc_insertion_point(module_scope)
