"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc as _abc_1
import sys
import typing as _typing
from collections import abc as _abc

import grpc as _grpc
from grpc import aio as _aio

from . import contextunit_pb2 as _contextunit_pb2

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...
class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ShieldServiceStub:
    """=====================================================
    ContextShield Service - AI Firewall & Security Authority
    =====================================================
    Security scanning, policy evaluation, compliance,
    audit, delegation chain management, and SECRET MANAGEMENT.
    All endpoints use ContextUnit as the transport envelope.
    =====================================================
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ShieldServiceAsyncStub: ...
    Scan: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Scan text for prompt injection, jailbreak, PII leaks
    Request payload: {text, context?, validators?: ["pii","rag_context"]}
    Response payload: {allowed, blocked, threats: [...], risk_score, severity, latency_ms}
    """
    GetStats: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Get service health and statistics
    Request payload: {}
    Response payload: {active_tokens, policies_loaded, audit_events_total, ...}
    """
    GetSecret: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=====================================================
    Secret Management RPCs
    =====================================================
    All operations require ContextToken with appropriate
    "secrets:read" or "secrets:write" permission.
    Secret values are encrypted at rest and NEVER logged.
    =====================================================

    GetSecret — Read a secret value by path
    Request payload: { path: string, version?: int, tenant_id?: string }
    Response payload: { path, value, version, created_at, expires_at, tags, encryption_backend }
    """
    PutSecret: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """PutSecret — Store or update a secret
    Request payload: { path: string, value: string, tags?: {}, ttl_seconds?: int, tenant_id?: string }
    Response payload: { path, version, created_at, expires_at }
    """
    ListSecrets: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """ListSecrets — List secret paths and metadata (NO values)
    Request payload: { prefix?: string, tenant_id?: string }
    Response payload: { secrets: [{ path, version, created_at, expires_at, tags }] }
    """
    RotateSecret: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """RotateSecret — Create new version, optionally invalidate old
    Request payload: { path: string, new_value: string, invalidate_previous?: bool, tenant_id?: string }
    Response payload: { path, old_version, new_version, created_at }
    """
    Encrypt: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=====================================================
    General-Purpose Encryption RPCs
    =====================================================
    Allows any service to encrypt/decrypt arbitrary data
    using Shield's encryption backends WITHOUT accessing
    secret store.
    =====================================================

    Encrypt — Encrypt arbitrary data
    Request payload: { plaintext: string, backend?: "fernet"|"aes256"|"age"|"kms_transit" }
    Response payload: { ciphertext_b64: string, encryption_kid: string, algorithm: string }
    """
    Decrypt: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """Decrypt — Decrypt data encrypted by Shield
    Request payload: { ciphertext_b64: string }
    Response payload: { plaintext: string }
    """
    SyncProjectPolicy: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """=====================================================
    Per-Project PKI RPCs
    =====================================================
    Key management for per-project Ed25519 signing.
    Projects authenticate with CU_PROJECT_SECRET (HMAC)
    and receive Shield-signed session tokens.
    =====================================================

    Sync project policy given a manifest
    Request payload: { project_id, manifest_yaml }
    Response payload: { updated: true, allowed_permissions: [...] }
    """
    IssueSessionToken: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """IssueSessionToken — Project authenticates and gets a session token
    Request payload: { project_id: string, hmac_proof: string }
    Response payload: { session_token: string, kid: string, expires_at: float, permissions: [...] }
    """
    GetProjectPublicKey: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """GetProjectPublicKey — Router fetches a project's Ed25519 public key
    Request payload: { project_id: string }
    Response payload: { public_key_b64: string, algorithm: string, kid: string }
    """
    RotateProjectKey: _grpc.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]
    """RotateProjectKey — Rotate Ed25519 keypair for a project
    Request payload: { project_id: string }
    Response payload: { new_public_key_b64: string, kid: string, rotation_count: int }
    """

@_typing.type_check_only
class ShieldServiceAsyncStub(ShieldServiceStub):
    """=====================================================
    ContextShield Service - AI Firewall & Security Authority
    =====================================================
    Security scanning, policy evaluation, compliance,
    audit, delegation chain management, and SECRET MANAGEMENT.
    All endpoints use ContextUnit as the transport envelope.
    =====================================================
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Scan: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Scan text for prompt injection, jailbreak, PII leaks
    Request payload: {text, context?, validators?: ["pii","rag_context"]}
    Response payload: {allowed, blocked, threats: [...], risk_score, severity, latency_ms}
    """
    GetStats: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Get service health and statistics
    Request payload: {}
    Response payload: {active_tokens, policies_loaded, audit_events_total, ...}
    """
    GetSecret: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=====================================================
    Secret Management RPCs
    =====================================================
    All operations require ContextToken with appropriate
    "secrets:read" or "secrets:write" permission.
    Secret values are encrypted at rest and NEVER logged.
    =====================================================

    GetSecret — Read a secret value by path
    Request payload: { path: string, version?: int, tenant_id?: string }
    Response payload: { path, value, version, created_at, expires_at, tags, encryption_backend }
    """
    PutSecret: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """PutSecret — Store or update a secret
    Request payload: { path: string, value: string, tags?: {}, ttl_seconds?: int, tenant_id?: string }
    Response payload: { path, version, created_at, expires_at }
    """
    ListSecrets: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """ListSecrets — List secret paths and metadata (NO values)
    Request payload: { prefix?: string, tenant_id?: string }
    Response payload: { secrets: [{ path, version, created_at, expires_at, tags }] }
    """
    RotateSecret: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """RotateSecret — Create new version, optionally invalidate old
    Request payload: { path: string, new_value: string, invalidate_previous?: bool, tenant_id?: string }
    Response payload: { path, old_version, new_version, created_at }
    """
    Encrypt: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=====================================================
    General-Purpose Encryption RPCs
    =====================================================
    Allows any service to encrypt/decrypt arbitrary data
    using Shield's encryption backends WITHOUT accessing
    secret store.
    =====================================================

    Encrypt — Encrypt arbitrary data
    Request payload: { plaintext: string, backend?: "fernet"|"aes256"|"age"|"kms_transit" }
    Response payload: { ciphertext_b64: string, encryption_kid: string, algorithm: string }
    """
    Decrypt: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """Decrypt — Decrypt data encrypted by Shield
    Request payload: { ciphertext_b64: string }
    Response payload: { plaintext: string }
    """
    SyncProjectPolicy: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """=====================================================
    Per-Project PKI RPCs
    =====================================================
    Key management for per-project Ed25519 signing.
    Projects authenticate with CU_PROJECT_SECRET (HMAC)
    and receive Shield-signed session tokens.
    =====================================================

    Sync project policy given a manifest
    Request payload: { project_id, manifest_yaml }
    Response payload: { updated: true, allowed_permissions: [...] }
    """
    IssueSessionToken: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """IssueSessionToken — Project authenticates and gets a session token
    Request payload: { project_id: string, hmac_proof: string }
    Response payload: { session_token: string, kid: string, expires_at: float, permissions: [...] }
    """
    GetProjectPublicKey: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """GetProjectPublicKey — Router fetches a project's Ed25519 public key
    Request payload: { project_id: string }
    Response payload: { public_key_b64: string, algorithm: string, kid: string }
    """
    RotateProjectKey: _aio.UnaryUnaryMultiCallable[_contextunit_pb2.ContextUnit, _contextunit_pb2.ContextUnit]  # type: ignore[assignment]
    """RotateProjectKey — Rotate Ed25519 keypair for a project
    Request payload: { project_id: string }
    Response payload: { new_public_key_b64: string, kid: string, rotation_count: int }
    """

class ShieldServiceServicer(metaclass=_abc_1.ABCMeta):
    """=====================================================
    ContextShield Service - AI Firewall & Security Authority
    =====================================================
    Security scanning, policy evaluation, compliance,
    audit, delegation chain management, and SECRET MANAGEMENT.
    All endpoints use ContextUnit as the transport envelope.
    =====================================================
    """

    @_abc_1.abstractmethod
    def Scan(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Scan text for prompt injection, jailbreak, PII leaks
        Request payload: {text, context?, validators?: ["pii","rag_context"]}
        Response payload: {allowed, blocked, threats: [...], risk_score, severity, latency_ms}
        """

    @_abc_1.abstractmethod
    def GetStats(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Get service health and statistics
        Request payload: {}
        Response payload: {active_tokens, policies_loaded, audit_events_total, ...}
        """

    @_abc_1.abstractmethod
    def GetSecret(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=====================================================
        Secret Management RPCs
        =====================================================
        All operations require ContextToken with appropriate
        "secrets:read" or "secrets:write" permission.
        Secret values are encrypted at rest and NEVER logged.
        =====================================================

        GetSecret — Read a secret value by path
        Request payload: { path: string, version?: int, tenant_id?: string }
        Response payload: { path, value, version, created_at, expires_at, tags, encryption_backend }
        """

    @_abc_1.abstractmethod
    def PutSecret(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """PutSecret — Store or update a secret
        Request payload: { path: string, value: string, tags?: {}, ttl_seconds?: int, tenant_id?: string }
        Response payload: { path, version, created_at, expires_at }
        """

    @_abc_1.abstractmethod
    def ListSecrets(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """ListSecrets — List secret paths and metadata (NO values)
        Request payload: { prefix?: string, tenant_id?: string }
        Response payload: { secrets: [{ path, version, created_at, expires_at, tags }] }
        """

    @_abc_1.abstractmethod
    def RotateSecret(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """RotateSecret — Create new version, optionally invalidate old
        Request payload: { path: string, new_value: string, invalidate_previous?: bool, tenant_id?: string }
        Response payload: { path, old_version, new_version, created_at }
        """

    @_abc_1.abstractmethod
    def Encrypt(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=====================================================
        General-Purpose Encryption RPCs
        =====================================================
        Allows any service to encrypt/decrypt arbitrary data
        using Shield's encryption backends WITHOUT accessing
        secret store.
        =====================================================

        Encrypt — Encrypt arbitrary data
        Request payload: { plaintext: string, backend?: "fernet"|"aes256"|"age"|"kms_transit" }
        Response payload: { ciphertext_b64: string, encryption_kid: string, algorithm: string }
        """

    @_abc_1.abstractmethod
    def Decrypt(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """Decrypt — Decrypt data encrypted by Shield
        Request payload: { ciphertext_b64: string }
        Response payload: { plaintext: string }
        """

    @_abc_1.abstractmethod
    def SyncProjectPolicy(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """=====================================================
        Per-Project PKI RPCs
        =====================================================
        Key management for per-project Ed25519 signing.
        Projects authenticate with CU_PROJECT_SECRET (HMAC)
        and receive Shield-signed session tokens.
        =====================================================

        Sync project policy given a manifest
        Request payload: { project_id, manifest_yaml }
        Response payload: { updated: true, allowed_permissions: [...] }
        """

    @_abc_1.abstractmethod
    def IssueSessionToken(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """IssueSessionToken — Project authenticates and gets a session token
        Request payload: { project_id: string, hmac_proof: string }
        Response payload: { session_token: string, kid: string, expires_at: float, permissions: [...] }
        """

    @_abc_1.abstractmethod
    def GetProjectPublicKey(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """GetProjectPublicKey — Router fetches a project's Ed25519 public key
        Request payload: { project_id: string }
        Response payload: { public_key_b64: string, algorithm: string, kid: string }
        """

    @_abc_1.abstractmethod
    def RotateProjectKey(
        self,
        request: _contextunit_pb2.ContextUnit,
        context: _ServicerContext,
    ) -> _typing.Union[_contextunit_pb2.ContextUnit, _abc.Awaitable[_contextunit_pb2.ContextUnit]]:
        """RotateProjectKey — Rotate Ed25519 keypair for a project
        Request payload: { project_id: string }
        Response payload: { new_public_key_b64: string, kid: string, rotation_count: int }
        """

def add_ShieldServiceServicer_to_server(
    servicer: ShieldServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]
) -> None: ...
