# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import contextunit_pb2 as contextunit__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in zero_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ZeroServiceStub(object):
    """=====================================================
    ContextZero Service - Privacy Proxy
    =====================================================
    PII anonymization, persona injection, and deanonymization.
    All endpoints use ContextUnit as the transport envelope.
    =====================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Anonymize = channel.unary_unary(
            "/contextunity.zero.ZeroService/Anonymize",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.Deanonymize = channel.unary_unary(
            "/contextunity.zero.ZeroService/Deanonymize",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.ScanPII = channel.unary_unary(
            "/contextunity.zero.ZeroService/ScanPII",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.ProcessPrompt = channel.unary_unary(
            "/contextunity.zero.ZeroService/ProcessPrompt",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.DestroySession = channel.unary_unary(
            "/contextunity.zero.ZeroService/DestroySession",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.GetStats = channel.unary_unary(
            "/contextunity.zero.ZeroService/GetStats",
            request_serializer=contextunit__pb2.ContextUnit.SerializeToString,
            response_deserializer=contextunit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )


class ZeroServiceServicer(object):
    """=====================================================
    ContextZero Service - Privacy Proxy
    =====================================================
    PII anonymization, persona injection, and deanonymization.
    All endpoints use ContextUnit as the transport envelope.
    =====================================================

    """

    def Anonymize(self, request, context):
        """Anonymize PII in a prompt before external LLM call
        Request payload: {prompt, session_id?, persona_name?, tenant_id}
        Response payload: {anonymized_prompt, entities_masked, entity_types, session_id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Deanonymize(self, request, context):
        """Deanonymize (restore PII) in an LLM response
        Request payload: {text, session_id}
        Response payload: {restored_text}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ScanPII(self, request, context):
        """Scan text for PII without modifying it
        Request payload: {text}
        Response payload: {contains_pii, entities_found, entity_types}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProcessPrompt(self, request, context):
        """Full pipeline: anonymize → (LLM call) → deanonymize in one call
        Request payload: {prompt, session_id?, persona_name?, llm_endpoint?}
        Response payload: {restored_response, audit: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DestroySession(self, request, context):
        """Destroy a session and wipe all keys from RAM
        Request payload: {session_id}
        Response payload: {destroyed: true}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStats(self, request, context):
        """Get service statistics (active sessions, encryption status)
        Request payload: {}
        Response payload: {active_sessions, total_processed, ...}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ZeroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Anonymize": grpc.unary_unary_rpc_method_handler(
            servicer.Anonymize,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "Deanonymize": grpc.unary_unary_rpc_method_handler(
            servicer.Deanonymize,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "ScanPII": grpc.unary_unary_rpc_method_handler(
            servicer.ScanPII,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "ProcessPrompt": grpc.unary_unary_rpc_method_handler(
            servicer.ProcessPrompt,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "DestroySession": grpc.unary_unary_rpc_method_handler(
            servicer.DestroySession,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
        "GetStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetStats,
            request_deserializer=contextunit__pb2.ContextUnit.FromString,
            response_serializer=contextunit__pb2.ContextUnit.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("contextunity.zero.ZeroService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("contextunity.zero.ZeroService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ZeroService(object):
    """=====================================================
    ContextZero Service - Privacy Proxy
    =====================================================
    PII anonymization, persona injection, and deanonymization.
    All endpoints use ContextUnit as the transport envelope.
    =====================================================

    """

    @staticmethod
    def Anonymize(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.zero.ZeroService/Anonymize",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Deanonymize(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.zero.ZeroService/Deanonymize",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ScanPII(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.zero.ZeroService/ScanPII",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ProcessPrompt(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.zero.ZeroService/ProcessPrompt",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DestroySession(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.zero.ZeroService/DestroySession",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextunity.zero.ZeroService/GetStats",
            contextunit__pb2.ContextUnit.SerializeToString,
            contextunit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
