# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import context_unit_pb2 as context__unit__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub(object):
    """=====================================================
    Admin Service - System Administration & Monitoring
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.
    =====================================================

    =========================================
    Service Health
    =========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServiceHealth = channel.unary_unary(
                '/contextunity.AdminService/GetServiceHealth',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.GetServiceMetrics = channel.unary_unary(
                '/contextunity.AdminService/GetServiceMetrics',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.CheckServiceConnectivity = channel.unary_unary(
                '/contextunity.AdminService/CheckServiceConnectivity',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.GetMemoryStats = channel.unary_unary(
                '/contextunity.AdminService/GetMemoryStats',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.GetMemoryLayerStats = channel.unary_unary(
                '/contextunity.AdminService/GetMemoryLayerStats',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/contextunity.AdminService/ListAgents',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.GetAgentConfig = channel.unary_unary(
                '/contextunity.AdminService/GetAgentConfig',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.UpdateAgentPermissions = channel.unary_unary(
                '/contextunity.AdminService/UpdateAgentPermissions',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.UpdateAgentTools = channel.unary_unary(
                '/contextunity.AdminService/UpdateAgentTools',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.GetAgentActivity = channel.unary_unary(
                '/contextunity.AdminService/GetAgentActivity',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.GetTraceDetails = channel.unary_unary(
                '/contextunity.AdminService/GetTraceDetails',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.SearchTraces = channel.unary_unary(
                '/contextunity.AdminService/SearchTraces',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.GetTraceChainOfThought = channel.unary_unary(
                '/contextunity.AdminService/GetTraceChainOfThought',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.GetSystemAnalytics = channel.unary_unary(
                '/contextunity.AdminService/GetSystemAnalytics',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.GetErrorAnalytics = channel.unary_unary(
                '/contextunity.AdminService/GetErrorAnalytics',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.DetectSystemErrors = channel.unary_unary(
                '/contextunity.AdminService/DetectSystemErrors',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.TriggerSelfHealing = channel.unary_unary(
                '/contextunity.AdminService/TriggerSelfHealing',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)
        self.GetHealingStatus = channel.unary_unary(
                '/contextunity.AdminService/GetHealingStatus',
                request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
                response_deserializer=context__unit__pb2.ContextUnit.FromString,
                _registered_method=True)


class AdminServiceServicer(object):
    """=====================================================
    Admin Service - System Administration & Monitoring
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.
    =====================================================

    =========================================
    Service Health
    =========================================
    """

    def GetServiceHealth(self, request, context):
        """Get health status of all services
        Request payload: {}
        Response payload: {services: {...}, timestamp: "..."}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceMetrics(self, request, context):
        """Get detailed metrics for a specific service
        Request payload: {service_endpoint: "..."}
        Response payload: {metrics: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckServiceConnectivity(self, request, context):
        """Test connectivity to a service
        Request payload: {service_endpoint: "..."}
        Response payload: {connected: bool, latency_ms: float}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryStats(self, request, context):
        """=========================================
        Memory Statistics
        =========================================

        Get statistics for all memory layers
        Request payload: {tenant_id?: "..."}
        Response payload: {memory_layers: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryLayerStats(self, request, context):
        """Get statistics for a specific memory layer
        Request payload: {layer: "...", tenant_id?: "..."}
        Response payload: {layer_stats: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """=========================================
        Agent Management
        =========================================

        List all registered agents
        Request payload: {service?: "...", tenant_id?: "..."}
        Response payload: {agents: [...], total: int}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentConfig(self, request, context):
        """Get configuration for a specific agent
        Request payload: {agent_id: "..."}
        Response payload: {agent: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgentPermissions(self, request, context):
        """Update permissions for an agent
        Request payload: {agent_id: "...", permissions: [...]}
        Response payload: {success: bool}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgentTools(self, request, context):
        """Update allowed/denied tools for an agent
        Request payload: {agent_id: "...", allowed_tools: [...], denied_tools: [...]}
        Response payload: {success: bool}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentActivity(self, request, context):
        """Get activity log for an agent
        Request payload: {agent_id: "...", hours?: int}
        Response payload: {activity: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTraceDetails(self, request, context):
        """=========================================
        Trace Management
        =========================================

        Get full trace details
        Request payload: {trace_id: "..."}
        Response payload: {trace_id: "...", events: [...], services: [...], duration_ms: int, status: "..."}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTraces(self, request, context):
        """Search traces by criteria
        Request payload: {service?: "...", agent_id?: "...", status?: "...", hours?: int}
        Response payload: {traces: [...], total: int}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTraceChainOfThought(self, request, context):
        """Get chain of thought for a trace
        Request payload: {trace_id: "..."}
        Response payload: {chain_of_thought: "..."}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemAnalytics(self, request, context):
        """=========================================
        Analytics
        =========================================

        Get system-wide analytics
        Request payload: {hours?: int}
        Response payload: {analytics: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorAnalytics(self, request, context):
        """Get error analytics
        Request payload: {hours?: int}
        Response payload: {errors: [...], total: int}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectSystemErrors(self, request, context):
        """=========================================
        Self-Healing
        =========================================

        Detect system errors
        Request payload: {error_id?: "..."}
        Response payload: {errors: [...], total: int}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerSelfHealing(self, request, context):
        """Trigger self-healing workflow
        Request payload: {error_id?: "..."}
        Response payload: {healing_id: "...", status: "..."}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealingStatus(self, request, context):
        """Get healing status
        Request payload: {healing_id: "..."}
        Response payload: {status: "...", progress: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServiceHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceHealth,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'GetServiceMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceMetrics,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'CheckServiceConnectivity': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckServiceConnectivity,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'GetMemoryStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryStats,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'GetMemoryLayerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryLayerStats,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'GetAgentConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentConfig,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'UpdateAgentPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgentPermissions,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'UpdateAgentTools': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgentTools,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'GetAgentActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentActivity,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'GetTraceDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTraceDetails,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'SearchTraces': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTraces,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'GetTraceChainOfThought': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTraceChainOfThought,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'GetSystemAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemAnalytics,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'GetErrorAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorAnalytics,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'DetectSystemErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectSystemErrors,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'TriggerSelfHealing': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSelfHealing,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
            'GetHealingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealingStatus,
                    request_deserializer=context__unit__pb2.ContextUnit.FromString,
                    response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contextunity.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contextunity.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """=====================================================
    Admin Service - System Administration & Monitoring
    =====================================================
    All methods use ContextUnit as input/output.
    Domain-specific data is passed via payload field.
    =====================================================

    =========================================
    Service Health
    =========================================
    """

    @staticmethod
    def GetServiceHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetServiceHealth',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetServiceMetrics',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckServiceConnectivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/CheckServiceConnectivity',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemoryStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetMemoryStats',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemoryLayerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetMemoryLayerStats',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/ListAgents',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetAgentConfig',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAgentPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/UpdateAgentPermissions',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAgentTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/UpdateAgentTools',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetAgentActivity',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTraceDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetTraceDetails',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTraces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/SearchTraces',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTraceChainOfThought(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetTraceChainOfThought',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetSystemAnalytics',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrorAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetErrorAnalytics',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectSystemErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/DetectSystemErrors',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerSelfHealing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/TriggerSelfHealing',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextunity.AdminService/GetHealingStatus',
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
