# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import context_unit_pb2 as context__unit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64min.proto\x12\x0c\x63ontextunity\x1a\x12\x63ontext_unit.proto2\xae\n\n\x0c\x41\x64minService\x12\x46\n\x10GetServiceHealth\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12G\n\x11GetServiceMetrics\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12N\n\x18\x43heckServiceConnectivity\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x44\n\x0eGetMemoryStats\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12I\n\x13GetMemoryLayerStats\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12@\n\nListAgents\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x44\n\x0eGetAgentConfig\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12L\n\x16UpdateAgentPermissions\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x46\n\x10UpdateAgentTools\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x46\n\x10GetAgentActivity\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x45\n\x0fGetTraceDetails\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x42\n\x0cSearchTraces\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12L\n\x16GetTraceChainOfThought\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12H\n\x12GetSystemAnalytics\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12G\n\x11GetErrorAnalytics\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12H\n\x12\x44\x65tectSystemErrors\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12H\n\x12TriggerSelfHealing\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x46\n\x10GetHealingStatus\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADMINSERVICE']._serialized_start=50
  _globals['_ADMINSERVICE']._serialized_end=1376
# @@protoc_insertion_point(module_scope)
