# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from contextcore import brain_pb2 as brain__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in brain_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BrainServiceStub(object):
    """=====================================================
    Core Brain Service Definition
    =====================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
            "/contextbrain.BrainService/Search",
            request_serializer=brain__pb2.SearchRequest.SerializeToString,
            response_deserializer=brain__pb2.SearchResponse.FromString,
            _registered_method=True,
        )
        self.GraphSearch = channel.unary_unary(
            "/contextbrain.BrainService/GraphSearch",
            request_serializer=brain__pb2.GraphSearchRequest.SerializeToString,
            response_deserializer=brain__pb2.GraphSearchResponse.FromString,
            _registered_method=True,
        )
        self.CreateKGRelation = channel.unary_unary(
            "/contextbrain.BrainService/CreateKGRelation",
            request_serializer=brain__pb2.CreateKGRelationRequest.SerializeToString,
            response_deserializer=brain__pb2.CreateKGRelationResponse.FromString,
            _registered_method=True,
        )


class BrainServiceServicer(object):
    """=====================================================
    Core Brain Service Definition
    =====================================================

    """

    def Search(self, request, context):
        """Semantic/Hybrid search"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GraphSearch(self, request, context):
        """Graph Traversal"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateKGRelation(self, request, context):
        """Create Knowledge Graph relation"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Search": grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=brain__pb2.SearchRequest.FromString,
            response_serializer=brain__pb2.SearchResponse.SerializeToString,
        ),
        "GraphSearch": grpc.unary_unary_rpc_method_handler(
            servicer.GraphSearch,
            request_deserializer=brain__pb2.GraphSearchRequest.FromString,
            response_serializer=brain__pb2.GraphSearchResponse.SerializeToString,
        ),
        "CreateKGRelation": grpc.unary_unary_rpc_method_handler(
            servicer.CreateKGRelation,
            request_deserializer=brain__pb2.CreateKGRelationRequest.FromString,
            response_serializer=brain__pb2.CreateKGRelationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "contextbrain.BrainService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "contextbrain.BrainService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class BrainService(object):
    """=====================================================
    Core Brain Service Definition
    =====================================================

    """

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextbrain.BrainService/Search",
            brain__pb2.SearchRequest.SerializeToString,
            brain__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GraphSearch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextbrain.BrainService/GraphSearch",
            brain__pb2.GraphSearchRequest.SerializeToString,
            brain__pb2.GraphSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateKGRelation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextbrain.BrainService/CreateKGRelation",
            brain__pb2.CreateKGRelationRequest.SerializeToString,
            brain__pb2.CreateKGRelationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
