# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from contextcore import commerce_pb2 as commerce__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in commerce_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CommerceServiceStub(object):
    """=====================================================
    Commerce Service Definition
    =====================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduct = channel.unary_unary(
            "/contextcommerce.CommerceService/GetProduct",
            request_serializer=commerce__pb2.GetProductRequest.SerializeToString,
            response_deserializer=commerce__pb2.ProductResponse.FromString,
            _registered_method=True,
        )
        self.UpdateProduct = channel.unary_unary(
            "/contextcommerce.CommerceService/UpdateProduct",
            request_serializer=commerce__pb2.UpdateProductRequest.SerializeToString,
            response_deserializer=commerce__pb2.ProductResponse.FromString,
            _registered_method=True,
        )
        self.GetProducts = channel.unary_unary(
            "/contextcommerce.CommerceService/GetProducts",
            request_serializer=commerce__pb2.GetProductsRequest.SerializeToString,
            response_deserializer=commerce__pb2.GetProductsResponse.FromString,
            _registered_method=True,
        )
        self.UpsertDealerProduct = channel.unary_unary(
            "/contextcommerce.CommerceService/UpsertDealerProduct",
            request_serializer=commerce__pb2.UpsertDealerProductRequest.SerializeToString,
            response_deserializer=commerce__pb2.UpsertDealerProductResponse.FromString,
            _registered_method=True,
        )
        self.UpdateEnrichment = channel.unary_unary(
            "/contextcommerce.CommerceService/UpdateEnrichment",
            request_serializer=commerce__pb2.UpdateEnrichmentRequest.SerializeToString,
            response_deserializer=commerce__pb2.UpdateEnrichmentResponse.FromString,
            _registered_method=True,
        )
        self.TriggerHarvest = channel.unary_unary(
            "/contextcommerce.CommerceService/TriggerHarvest",
            request_serializer=commerce__pb2.HarvestRequest.SerializeToString,
            response_deserializer=commerce__pb2.HarvestResponse.FromString,
            _registered_method=True,
        )
        self.GetPendingVerifications = channel.unary_stream(
            "/contextcommerce.CommerceService/GetPendingVerifications",
            request_serializer=commerce__pb2.PendingRequest.SerializeToString,
            response_deserializer=commerce__pb2.PendingItem.FromString,
            _registered_method=True,
        )
        self.SubmitVerification = channel.unary_unary(
            "/contextcommerce.CommerceService/SubmitVerification",
            request_serializer=commerce__pb2.VerificationResult.SerializeToString,
            response_deserializer=commerce__pb2.VerificationAck.FromString,
            _registered_method=True,
        )


class CommerceServiceServicer(object):
    """=====================================================
    Commerce Service Definition
    =====================================================

    """

    def GetProduct(self, request, context):
        """Product CRUD"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProducts(self, request, context):
        """Dealer Products (Harvester)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpsertDealerProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateEnrichment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TriggerHarvest(self, request, context):
        """Harvester trigger"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPendingVerifications(self, request, context):
        """Gardener: Get items needing classification"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubmitVerification(self, request, context):
        """Gardener: Write enrichment results"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CommerceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetProduct": grpc.unary_unary_rpc_method_handler(
            servicer.GetProduct,
            request_deserializer=commerce__pb2.GetProductRequest.FromString,
            response_serializer=commerce__pb2.ProductResponse.SerializeToString,
        ),
        "UpdateProduct": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateProduct,
            request_deserializer=commerce__pb2.UpdateProductRequest.FromString,
            response_serializer=commerce__pb2.ProductResponse.SerializeToString,
        ),
        "GetProducts": grpc.unary_unary_rpc_method_handler(
            servicer.GetProducts,
            request_deserializer=commerce__pb2.GetProductsRequest.FromString,
            response_serializer=commerce__pb2.GetProductsResponse.SerializeToString,
        ),
        "UpsertDealerProduct": grpc.unary_unary_rpc_method_handler(
            servicer.UpsertDealerProduct,
            request_deserializer=commerce__pb2.UpsertDealerProductRequest.FromString,
            response_serializer=commerce__pb2.UpsertDealerProductResponse.SerializeToString,
        ),
        "UpdateEnrichment": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateEnrichment,
            request_deserializer=commerce__pb2.UpdateEnrichmentRequest.FromString,
            response_serializer=commerce__pb2.UpdateEnrichmentResponse.SerializeToString,
        ),
        "TriggerHarvest": grpc.unary_unary_rpc_method_handler(
            servicer.TriggerHarvest,
            request_deserializer=commerce__pb2.HarvestRequest.FromString,
            response_serializer=commerce__pb2.HarvestResponse.SerializeToString,
        ),
        "GetPendingVerifications": grpc.unary_stream_rpc_method_handler(
            servicer.GetPendingVerifications,
            request_deserializer=commerce__pb2.PendingRequest.FromString,
            response_serializer=commerce__pb2.PendingItem.SerializeToString,
        ),
        "SubmitVerification": grpc.unary_unary_rpc_method_handler(
            servicer.SubmitVerification,
            request_deserializer=commerce__pb2.VerificationResult.FromString,
            response_serializer=commerce__pb2.VerificationAck.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "contextcommerce.CommerceService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "contextcommerce.CommerceService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CommerceService(object):
    """=====================================================
    Commerce Service Definition
    =====================================================

    """

    @staticmethod
    def GetProduct(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextcommerce.CommerceService/GetProduct",
            commerce__pb2.GetProductRequest.SerializeToString,
            commerce__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateProduct(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextcommerce.CommerceService/UpdateProduct",
            commerce__pb2.UpdateProductRequest.SerializeToString,
            commerce__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetProducts(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextcommerce.CommerceService/GetProducts",
            commerce__pb2.GetProductsRequest.SerializeToString,
            commerce__pb2.GetProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpsertDealerProduct(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextcommerce.CommerceService/UpsertDealerProduct",
            commerce__pb2.UpsertDealerProductRequest.SerializeToString,
            commerce__pb2.UpsertDealerProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateEnrichment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextcommerce.CommerceService/UpdateEnrichment",
            commerce__pb2.UpdateEnrichmentRequest.SerializeToString,
            commerce__pb2.UpdateEnrichmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TriggerHarvest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextcommerce.CommerceService/TriggerHarvest",
            commerce__pb2.HarvestRequest.SerializeToString,
            commerce__pb2.HarvestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPendingVerifications(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextcommerce.CommerceService/GetPendingVerifications",
            commerce__pb2.PendingRequest.SerializeToString,
            commerce__pb2.PendingItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubmitVerification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextcommerce.CommerceService/SubmitVerification",
            commerce__pb2.VerificationResult.SerializeToString,
            commerce__pb2.VerificationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
