# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import context_unit_pb2 as context__unit__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in router_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RouterServiceStub(object):
    """=====================================================
    Router Service - AI Agent Orchestration
    =====================================================
    All methods use ContextUnit as input/output.
    Agent identification and input is passed via payload.
    =====================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteAgent = channel.unary_unary(
            "/contextrouter.RouterService/ExecuteAgent",
            request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            response_deserializer=context__unit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )
        self.StreamAgent = channel.unary_stream(
            "/contextrouter.RouterService/StreamAgent",
            request_serializer=context__unit__pb2.ContextUnit.SerializeToString,
            response_deserializer=context__unit__pb2.ContextUnit.FromString,
            _registered_method=True,
        )


class RouterServiceServicer(object):
    """=====================================================
    Router Service - AI Agent Orchestration
    =====================================================
    All methods use ContextUnit as input/output.
    Agent identification and input is passed via payload.
    =====================================================

    """

    def ExecuteAgent(self, request, context):
        """Execute a single turn of an agent
        Request payload: {tenant_id, agent_id, input_text, context?: {...}}
        Response payload: {output_text, tool_calls?: {...}, metadata?: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamAgent(self, request, context):
        """Stream agent execution (for UI with real-time output)
        Request payload: {tenant_id, agent_id, input_text, context?: {...}}
        Response payload: {output_text, tool_calls?: {...}, metadata?: {...}}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecuteAgent": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteAgent,
            request_deserializer=context__unit__pb2.ContextUnit.FromString,
            response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
        ),
        "StreamAgent": grpc.unary_stream_rpc_method_handler(
            servicer.StreamAgent,
            request_deserializer=context__unit__pb2.ContextUnit.FromString,
            response_serializer=context__unit__pb2.ContextUnit.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "contextrouter.RouterService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "contextrouter.RouterService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RouterService(object):
    """=====================================================
    Router Service - AI Agent Orchestration
    =====================================================
    All methods use ContextUnit as input/output.
    Agent identification and input is passed via payload.
    =====================================================

    """

    @staticmethod
    def ExecuteAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/contextrouter.RouterService/ExecuteAgent",
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/contextrouter.RouterService/StreamAgent",
            context__unit__pb2.ContextUnit.SerializeToString,
            context__unit__pb2.ContextUnit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
