# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shield.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shield.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import context_unit_pb2 as context__unit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cshield.proto\x12\rcontextshield\x1a\x12\x63ontext_unit.proto2\xa9\x07\n\rShieldService\x12:\n\x04Scan\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x44\n\x0e\x45valuatePolicy\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x45\n\x0f\x43heckCompliance\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x41\n\x0bRecordAudit\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12?\n\tMintToken\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x41\n\x0bVerifyToken\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x41\n\x0bRevokeToken\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12>\n\x08GetStats\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12?\n\tGetSecret\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12?\n\tPutSecret\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x41\n\x0bListSecrets\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x42\n\x0cRotateSecret\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12=\n\x07\x45ncrypt\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12=\n\x07\x44\x65\x63rypt\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shield_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHIELDSERVICE']._serialized_start=52
  _globals['_SHIELDSERVICE']._serialized_end=989
# @@protoc_insertion_point(module_scope)
