# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zero.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'zero.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import context_unit_pb2 as context__unit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nzero.proto\x12\x0b\x63ontextzero\x1a\x12\x63ontext_unit.proto2\x9b\x03\n\x0bZeroService\x12?\n\tAnonymize\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x41\n\x0b\x44\x65\x61nonymize\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12=\n\x07ScanPII\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x43\n\rProcessPrompt\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12\x44\n\x0e\x44\x65stroySession\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnit\x12>\n\x08GetStats\x12\x18.contextcore.ContextUnit\x1a\x18.contextcore.ContextUnitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zero_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ZEROSERVICE']._serialized_start=48
  _globals['_ZEROSERVICE']._serialized_end=459
# @@protoc_insertion_point(module_scope)
